### ISSUE TITLE
Can zsim run shell program and dbt2 benchmark

### ISSUE THREAD

**Issue by cyjseagull** [s5z/zsim#100]
As you know, many OTLP bencharks, such as TPC-C, TPC-H are started and handled by some shell scripts, for example, dbt2 benchmark lanuching script is a totally shell program. When I ran dbt2 with zsim, there are continuous error, just like this:
" pin_kit/source/include/pin/gen/exception.PH:GetFaultyAccessAddress:GetFaultyAccessAddress:242: assertion failed: IsAccessFault()  ".
So I want to know can zsim run shell program? If can, how can they ran them ?

**Comment by s5z** [comment]
Yes, zsim can run scripts. See tests/ptree.cfg. It looks like you are running into a Pin problem. Try to run the workload under Pin; if it fails, file a bug with Pin.

**Comment by cyjseagull** [comment]
Thank you very much! I can run shell scripts with zsim successfully!
