### ISSUE TITLE
simulation terminated with "gm_malloc(): Out of global heap memory, use a larger GM segment"

### ISSUE THREAD

**Issue by cyjseagull** [s5z/zsim#102]
hello,
      I am doing some experiments with zsim these days. I ran large footprint benchmark such as Dictionary and Nbody ( both are selected from Problem Based Benchmark ) with zsim (gmMBytes is set to be 8192MB), however, the simulation teminated with "gm_malloc(): Out of global heap memory, use a larger GM segment", I realize that global memory allocation with gm_malloc() is failed. So I modified gm_malloc(), add "panic" in all functions that invoke gm_malloc(), and ran all the benchmark again. Result shows that all simulation are teminated because of "curSlab = static_cast<Slab*>gm_malloc(sizeof(Slab)+slabSize)", that is to say, there is no continuous "sizeof(Slab)+slabSize" space for "curSlab", How can solve this problem? Looking forward to your response!

**Comment by s5z** [comment]
What config are you running with? How many cores, and what is phaseLength? Did you add/change any timing models? That looks like timing events are exhausting simulator memory. There might be a leak (if events don't get deleted), or you may just need more space or shorter phases.

**Comment by cyjseagull** [comment]
I have set 4 cores, phaseLength is 10000 and statsPhaseInterval is 1000. I used nvmain as the simulator, and modified nvmain code to implement a new physical memory structure, I guess maybe there is something wrong with nvmain simulation.
