### ISSUE TITLE
Zero latency for Terminal Caches

### ISSUE THREAD

**Issue by vijay4454** [s5z/zsim#104]
Hello

In init.cpp, I found the following code:

** uint32_t accLat = (isTerminal)? 0 : latency; //terminal caches has no access latency b/c it is assumed accLat is hidden by the pipeline**

Essentially, this overrides the configured latency of all terminal caches (L1 I and D caches) and replaces with 0. Because of this, all L1 icache and dcache accesses take 1 cycle regardless of it's frequency (bbl() code in simple_core.cpp adds 1 cycle for all instructions, including loads and stores, so it's not really 0 cycles for L1 hits).

I am wondering what is the reason for this design decision. A core running at a high frequency like 3GHz takes about 4 cycles for L1 cache hit.

**Comment by vijay4454** [comment]
I think I get it. The OoO core running at a high frequency is not usually sensitive to L1 latency as it is good at hiding it.

**Comment by s5z** [comment]
The reason for this design decision is in the comment you copy-pasted: it is assumed accLat is hidden by the pipeline. If you look on ooo_core.h/cpp, you'll see that the latency is considered there (and it is, in fact, 4 cycles as you mention). Simple and Timing are IPC-1 cores, which means 1 cycle for everything except cache misses. The cache latency still matters for invalidations.
