### ISSUE TITLE
SPECCPU 2006 inSyscall 0 error

### ISSUE THREAD

**Issue by faromero** [s5z/zsim#105]
When I run some SPECCPU 2006 benchmarks, such as 436.cactusADM, 434.zeusmp, and 400.perlbench, I get the following error:

[S 0] WARN: [0] ContextChange, reason FATAL_SIGNAL, inSyscall 0
[S 0] [0] Fatal signal caught, finishing
[S 0] Dumping termination stats
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] [watchdog] Deferring cleanup of pid 0 (18731), not finished yet
[S 0] Finished scheduler watchdog thread
[H] Child 18731 done
[H] All children done, exiting

These benchmarks were previously simulating correctly but are now giving me this error. I have tried with and without fast-forwarding instructions and it gives me the same issue, and I am running it on a single-core configuration. What could be causing this error?

**Comment by s5z** [comment]
Never seen this before. Since it was working before and now it's not, perhaps you changed something in your system config? Maybe you're running out of memory? If you can determine this is a problem in zsim and not your system, please reopen.

**Comment by stevenflo** [comment]
I am having a similar issue with Zsim on a fresh installation. Has anyone encountered or fixed this bug for. I am specifically running Zsim with lmbench.

**Comment by ivanfv** [comment]
I get this error when I try to simulate an executable that crashes at the very begging due to a missing argument
