### ISSUE TITLE
Panic on build/opt/zsim_harness.cpp:122: Child 11649 (idx 0) exit was anomalous, killing simulation

### ISSUE THREAD

**Issue by cyjseagull** [s5z/zsim#106]
hello, 
      When I run benchmarks with zsim , some large footprint benchmarks will  exit abnormally with panic "Panic on build/opt/zsim_harness.cpp:122: Child 11649 (idx 0) exit was anomalous, killing simulation", I have checked codes of "zsim_harness.cpp:122", it showed that notifyEnd has not been called before program exits. Then, what kind of unproper operation will cause this kind of panic ? Is there some method to log some useful information about simulated program before simulation ended with this panic? Looking forward to your helpful response!

**Comment by s5z** [comment]
Typically it's one of the zsim processes causing an assertion, panic, or segfault. Do you see any error message other than this one?

If you don't can you run with sim.attachDebugger = true and see whether you get some sort of signal before the abnormal termination?

**Comment by cyjseagull** [comment]
Thank you very much. I think I have figured out the reason, it's because that I have simulated too many instructions, as a result, memory has been exhausted, simulation terminated finally. After I set MaxTotalInsts with reasonable number, all simulations are completed normally. Next time, when I run zsim, I will set sim.attachDebugger = true to get more detailed information about abnormal terminaltion. Thanks again for your guidance.

**Comment by s5z** [comment]
Alright, please reopen if it's a zsim bug.

**Comment by jyffly** [comment]
I set maxTotalInstrs = 1000L, but I have still the same problem, could you tell me your detail sets ,thanks.@cyjseagull

**Comment by GowthamD909** [comment]
Panic on build/opt/zsim_harness.cpp:123: Child 26942 (idx 0) exit was anomalous, killing simulation

I am getting this issue while trying to run DAMOV with  
./build/opt/zsim config_files/pim_inorder/stream/1/Add_Add.cfg
i have changed sim.attachDebugger = true but its not resolved
