### ISSUE TITLE
Micro-op Trace

### ISSUE THREAD

**Issue by vijay4454** [s5z/zsim#107]
Hello

I am doing some micro-benchmarking on the OoO core configuration and observe some weird behavior where zsim is counting 1 more micro-op than expected in a tight loop of 4 instructions. I need to figure out the micro-op breakdown of each macro-op seen by zsim. Is there a micro-op tracing/dump feature in zsim that I could use?

Vijay

**Comment by s5z** [comment]
This is not quite supported but you can add it quite easily. Look in decoder.h/cpp, in particular at the BBL_PROFILING ifdefs.
