### ISSUE TITLE
Can Zsim run SPEC CPU2006 pinballs like Sniper

### ISSUE THREAD

**Issue by cyjseagull** [s5z/zsim#108]
hello:
     I am running SPEC CPU2006 with zsim these days, however, most of spec cpu benchmark are with  large instruction num, which means it will take much time to simulate them. Althrough the max simulation instructions can be set to cut down simulation time, but I think it's not representative, because even 2 billion instructions have been simulated, it only occupies no more than 1% instructions of whole mcf. Since intel pinpoint can run most representive part of programs, can zsim support pinpoints, and run SPEC CPU2006 pinballs like Sniper. Looking forward to your response.

**Comment by s5z** [comment]
You can run simpoints quite easily with ffiPoints. Figure out the instruction start/end points for each benchmark, then use:

processX = {
   ...
   startFastForwarded = true;
   ffiPoint = "simpoint0Start simpoint0End-simpoint0Start ...";
}

We don't support pinballs at the moment, but I guess they should be easy to add (and while I see how this can be appealing if you're looking to save a few cycles, I'd recommend you embrace non-determinism in the benchmark and run multiple times to achieve tight confidence intervals instead).

**Comment by cyjseagull** [comment]
I know how to run benchmarks with large instructions more accurately thanks to your response. Thank you very much!

**Comment by lwj0012** [comment]
@cyjseagull did you figure out how to use simpoints in zsim? Could you share your method? Thanks.

**Comment by cyjseagull** [comment]
I have added simpoint support in my code, you can find it in URL: https://github.com/cyjseagull/SHMA. The main method is:
1. get simpoint of benchmarks with **valgrind** and **simpoint**, the simpoint source code can be downloaded from **https://github.com/southerngs/simpoint**, usage of simpoint can be found in **http://www.lxway.com/66689156.htm** and **http://cseweb.ucsd.edu/~calder/simpoint/multiple-standard-simpoints.htm**

2. add "**startFastForwarded=true**" and "**simPoints=path of simpoints**" configurations in process section after modified your code. As described in main page of https://github.com/cyjseagull/SHMA

The main modification of zsim is "process_tree.cpp", which has added simpoints files parse function, you can view "process_tree.cpp" to figure out how simpoints files are parsed.

**Comment by lwj0012** [comment]
@cyjseagull Thanks a lot! And did you use SHMA in any publications?
