### ISSUE TITLE
Number of Cache Ports

### ISSUE THREAD

**Issue by vijay4454** [s5z/zsim#110]
I want to be able to configure the number of read/write, read-only,write-only ports for each cache in the system. It doesn't look like it is possible to do so. If that is true, what does zsim assume for number of cache ports? This will have affect on performance if two cache accesses happen in the same cycle to the same cache bank. 

Could someone please point me to the right source code that I could gawk and potentially modify to implement this feature?

**Comment by s5z** [comment]
TimingCache assumes a single port. When we want more bandwidth, we use more banks. Cache ports are expensive... what is your use case? If you want to model a multi-ported cache, and multi-banking doesn't do it for you, you'd need to modify timing_cache.h/cpp or create your own model.
