### ISSUE TITLE
ZSim Scheduler Parameters

### ISSUE THREAD

**Issue by dzhang50** [s5z/zsim#111]
ZSim isn't properly modeling the effects of contention on multithreaded graph applications (scaling factor is too good compared to real hardware). I'm trying to fix this by tweaking the scheduler. How can I do this? How do switches such as sim.schedQuantum, sim.contentionThreads, sim.parallelism, sim.domains, sim.phaseLength, etc. affect results? Any insights on what I should tweak?

**Comment by s5z** [comment]
If it's bandwidth contention we're talking about, you should use timing models with a weave phase (DDR mem, Timing cache, OOO core).

If you have very fine-grain read-write sharing going on, it's possible your simulation is not accurate enough (see our ISCA 2013 paper or the MICRO 2015 tutorial for a description of the bound-weave technique and it limitations). The key parameter to tweak here is phaseLength. Try with a lower phaseLength (down to 1000 or 100 cycles) and see whether there's improvement. That said, we see this very rarely, even in irregular programs like bfs/sssp.

The other parameters will have a minor effect, if at all. sim.parallelism controls the number of concurrent threads in the bound phase (should not significantly affect results with a low enough phaseLength). sim.domains and sim.contentionThreads control weave-phase concurrency, and don't change correctness. sim.schedQuantum has to do with the thread-to-core scheduler, and only comes into play when you spawn more threads than cores.

**Comment by apoorvaaaa5** [comment]
hey, i am new to zsim and even i am encountering the same. i am trying for bfs algorithm and the scaling seems to be too good. could you help me more about how should i do fine grain analysis to under the performance better??
