### ISSUE TITLE
Termination condition for multiprocess workloads

### ISSUE THREAD

**Issue by nhkim11** [s5z/zsim#112]
I am running multiprocess workloads on zsim and configure it like explained in #101.

ffiPoints = "2000000 10000000000000";
dumpInstrs = 50000000L;
startFastForwarded = True;
for each process and set sim.maxProcEventualDumps = number of processes

I expect that all processes fast-forward 2M instructions and report stats for first 50M instructions (all instrs of each core in zsim-ev.h5 shows ~50M) even if they actually run until all processes reach 50M instructions.
However, zsim-ev.h5 seems to report final stat when all processes reaches 50M instructions.

How can I fix this? 
Thanks.

**Comment by s5z** [comment]
That should be working. Perhaps you are only looking at the final sample of zsim-ev.h5? Note that each time a processes reaches dumpInstrs, it dumps a new sample of *all the stats* in the system. So you need to combine data from multiple samples. You can identify which process triggered the sample through the "trigger" field in the stats.
