### ISSUE TITLE
Three questions about ZSIM

### ISSUE THREAD

**Issue by mengnanpeter** [s5z/zsim#115]
Dear All,
     Thank you very much for your attention. As I am new to this simulator, I have some questions as the following show:
     1. We put some instructions respectively in the "process0={}, process1={},.....,processN={}" part in .cfg file when we want to run more than one applications. Do these processes run parallel? When we run a parallel application (e.g. blackscholes in parsec) in one process, does it mean that this application will be running in just one core, so the thread number will be limited?

```
 2. Is there any tools integrated to measure the power, area and so on (e.g mcpat)?

 3. In the ZSIM slide  "configuration and stats", it shows some plots of stats. I would like to know whether exist some tools in ZSIM that can plot according to the output result?

 Thank you very much for your answer.
```

**Comment by mengnanpeter** [comment]
Sorry about the format.......

**Comment by s5z** [comment]
1. Yes, they run in parallel. If you run a parallel application, its threads can use multiple cores (e.g., you can have 4 16-thread applications running in a 64-core chip). If you launch more threads than cores, a basic round-robin scheduler time-multiplexes them across cores. If you want to control the core-thread mapping, use processX.procMask.
2. Not integrated, but you can easily feed zsim's event counts to McPAT or other modeling tools. 
3. See README.stats, it's a script that shows how to read the HDF5 stats from python using h5py. We use matplotlib to plot these stats.
