### ISSUE TITLE
MD1 Clamped Loads

### ISSUE THREAD

**Issue by vijay4454** [s5z/zsim#116]
My objective is to have a simple main memory model in zsim where I can configure a fixed latency and peak bandwidth. Depending on whether bandwidth is exceeded (and by how much), latency should be accordingly adjusted. I looks like the MD1Memory type does just that.

However, I don't quite understand the concept of "clampedLoads". Why is "load" in mem_ctrls.cpp line 90, clamped to 0.95 when it exceeds 0.95? Why not just "not clamp" it? I am guessing it has something to do with the queuing theory concept used here.

**Comment by s5z** [comment]
Under very high loads, MD1 starts producing really high latencies (e.g., 10Kcycles/request). The clampedLoads hack avoids these high latencies, which may come from a sudden spike in traffic, and causes them to be compensated over multiple phases.

Honestly, if you want something simpler than DDR, I'd code a weave-phase slot-based timing model: K slots per cycle, and each request takes the first N slots available, where K and N are determined by whatever bandwidth you want. This will model contention much more accurately than MD1, which was developed to model contention approximately before we had weave-phase models.
