### ISSUE TITLE
Secondary Memory Access

### ISSUE THREAD

**Issue by Dragonslair5** [s5z/zsim#118]
Does ZSIM account for the secondary memory access? I mean, if a program access files, does ZSIM count the amount of cycles needed to load the file to main memory? Or does it consider that every file is already loaded to main memory?

If so, is any way that I can simulate different  kinds of secondary memory, like using HDDs vs SSDs, using ZSIM?

**Comment by s5z** [comment]
We do not consider secondary storage; all page faults happen transparently to zsim, and non-blocking syscalls are assumed to happen in a single cycle. If you need to do this kind of analysis, I recommend you use a full-system simulator (e.g., gem5).
