### ISSUE TITLE
Weird "pinbin" permission denied issue

### ISSUE THREAD

**Issue by vijay4454** [s5z/zsim#127]
Hello

I am running into a frustrating issue. I am getting this error:

[H] Starting zsim, built Sat Jul 16 20:01:44 CDT 2016 (rev develop:28:3bfcd44:7fc 24+ 23- 02b2356b)
[H] Creating global segment, 1024 MBs
[H] Global segment shmid = 232718359
[H] Deadlock detection OFF
Could not exec, killing child: Permission denied
[H] Panic on build/opt/zsim_harness.cpp:301: Could not exec /u/t/h/thiruven/pin-2.14-67254-gcc.4.4.7-linux/intel64/bin/pinbin
[H] Child 7824 done
[H] Panic on build/opt/zsim_harness.cpp:118: Child issued a panic, killing simulation

What's weird is that this error doesn't show up every time. Sometimes it does, while sometimes it doesn't. Also, it's not just the "pinbin" which has the permission denied error, it's multiple other files, even those unrelated to the zsim simulation.

I wonder what's going on. Could it have something to do with the fact that I am using the "screen" utility for the simulations? I ssh remotely into my machine, startup a "screen" session, launch simulation, detach from that screen session and then log out. 

Any ideas what could be going on here? I think this is probably unrelated to zsim in particular.

Thanks
Vijay

**Comment by vijay4454** [comment]
This was not a zsim-specific issue. It was some permissions issue on my local filesystem.

**Comment by Taya666** [comment]
> This was not a zsim-specific issue. It was some permissions issue on my local filesystem.

HI ,have you solved this? 
I meat some problems similar to your.i run my config ,and then 


Starting zsim, built 2018年 12月 06日 星期四 17:28:38 CST (rev no git repo)
[H] Creating global segment, 4096 MBs
[H] Global segment shmid = 7569457
[H] Deadlock detection ON
launchprocess 0
cmd:/473.astar/exe/astar_base.amd64-m64-gcc43-nn
cmd:BigLakes2048.cfg
/home/taya/SHMA-master/zsim-nvmain/pin_kit/intel64/bin/pinbin -follow_execv -tool_exit_timeout 1 -t /home/taya/SHMA-master/zsim-nvmain/bin/libzsim.so -config /home/taya/SHMA-master/zsim-nvmain/config/shma-static.cfg -outputDir /home/taya/SHMA-master/zsim-nvmain -shmid 7569457 -logToFile -procIdx 0 -- /473.astar/exe/astar_base.amd64-m64-gcc43-nn BigLakes2048.cfg 
Could not exec, killing child: Permission denied
[H] Panic on build/opt/zsim_harness.cpp:300: Could not exec /home/taya/SHMA-master/zsim-nvmain/pin_kit/intel64/bin/pinbin
[H] Child 26291 done
[H] Panic on build/opt/zsim_harness.cpp:117: Child issued a panic, killing simulation

could u give me some help?
thanks you so much!
