### ISSUE TITLE
Reading Address contents

### ISSUE THREAD

**Issue by odanrc** [s5z/zsim#130]
I'm trying to access data written/read in the cache as portrayed on issue #6. 

Therefore, within the lookup (cache_array.cpp) function I try to read the contents of the lookup address, by treating the address as a pointer to the data I want, as in:

```
std::cout << "Address: " << std::hex << lineAddr << std::endl;
std::cout << "Contents: " << std::dec << *(Address*)lineAddr << std::endl;

```

However, this is wrong, as it makes me access invalid addresses.

```
Address: 1ffffffff7b
[S 0] [0] Internal exception detected:
[S 0] [0]  Code: 1
[S 0] [0]  Address: 0x7ffff63d829e
[S 0] [0]  Description: Exception Code: ACCESS_INVALID_ADDRESS. Exception Address = 0x7ffff63d829e. Access Type: UNKNOWN. Access Address = 0x1ffffffff7b

```

Does anyone have an idea of what I might be doing wrong?

Thanks in advance.

**Comment by gaomy3832** [comment]
As the name suggests, `lineAddr` is not the real address, but only the cacheline address part (i.e., shifted by `log2(lineSize)` bits. In addition, there is a hack to differentiate virtual addresses for different processes, which embeds a `procMask` in this `lineAddr`.

Take a look at filter_cache.h, load(), store(), and replace() functions, to see how a `vAddr` is made to `vLineAddr` then `pLineAddr`.

**Comment by odanrc** [comment]
Thank you for your help. Besides not shifting the address, I was trying to access the contents within a cache_array lookup(), even if it was a PUTX, which lead to invalid address access.
