### ISSUE TITLE
Updated LINUX

### ISSUE THREAD

**Issue by hristos93** [s5z/zsim#135]
Hi, i recently updated my linux from ubuntu 14.04 to 16.01 and when i try to run an example a get this:
E:4.4 is not a supported linux release

I updated my kernel to 4.6 to fix it but it sims that it didn't work at all as now i get this :
E:4.6 is not a supported linux release
Any idea ?

**Comment by grantae** [comment]
The error you're seeing is related to pin 2.x which doesn't run as-is on linux 4.x kernels (Ubuntu 16 upgraded from kernel 3.x to 4.x). Pin 3.0 works with kernel 4 and thus Ubuntu 16, however it also makes a lot of changes to the API and linking process for pin tools and this is currently incompatible with the way zsim is built. So for now, as far as I know, zsim does not work on any Linux 4.x systems including Ubuntu 16.

**Comment by hristos93** [comment]
any idea what should i do? if i find a way to downgrade my ubuntu version will it work again ?

**Comment by grantae** [comment]
It's up to you: Downgrade, VM with Ubuntu 14, patch zsim, etc.

Edit: Related issue #109

**Comment by hristos93** [comment]
thank you.
