### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by hristos93** [s5z/zsim#136]
Hi,
I would like to create my own .config file to simulate a Hybrid memory cube & a High bandwidth memory . I did my research and I came up with some issues like the way that I should use TSV's . Generally is there any manual to create my own config file ?

**Comment by gaomy3832** [comment]
If you run the sample cfg files coming with zsim you will find a `out.cfg` file in the run directory created by zsim. It lists all the default options that the input cfg file does not specify. You can use it as a reference. Also note that depending on some options (e.g., type of cache/memory), some other options may be different. So to get to know the details, you should study carefully `init.cpp` where the options in cfg file translate to system config.
