### ISSUE TITLE
drc_miss & rb_miss

### ISSUE THREAD

**Issue by hristos93** [s5z/zsim#141]
hi , i am comparing 3D mems and Dram but i can't understand what is the difference between those variables (drc and rb). In which one of those should i keep my focus?

**Comment by cyjseagull** [comment]
drc_miss is dram cache miss count; rb_miss is row buffer miss count.
If the 3D DRAM are used as cache of DRAM, then drc_miss may be your focus. If you are doing something related to row buffer hit rate improvement, then rb_miss may be your focus.

**Comment by hristos93** [comment]
hi cyjseagull, thank you very much for your help. I am using 3D DRAM cache , so you are right  because the miss rate of 3D cache is far lower then Drams .
