### ISSUE TITLE
Is there a way to reset stats during runtime?

### ISSUE THREAD

**Issue by ShehabElsayed** [s5z/zsim#147]
Let's say I want to reset the stats at the beginning of the ROI, is there a way to do this?

Thanks

**Comment by nrodia** [comment]
There may be a way to reset stats of which I am not aware, however, you can achieve the same effect by using the periodic stats functionality. You can get stats at different points during the simulation and subtract the accumulated stats from the earlier part of the simulation, before the "reset" point. 

Specifically, there is an eventual stats file (zsim-ev.h5) and a periodic stats file (zsim.h5). For more detail, see slide 19 in the configuration and stats slide deck from the MICRO '15 tutorial (http://zsim.csail.mit.edu/tutorial/). The frequency of stats dumps is controlled by the sim.statsPhaseInterval configuration parameter. You can also produce filtered periodic stats using the StatsFilter interface; see filter_stats.h/cpp.

**Comment by ShehabElsayed** [comment]
Thanks a lot

**Comment by nrodia** [comment]
If this has answered your question, please close the issue. Thanks!
