### ISSUE TITLE
The benchmarks parsec and speccpu are not found.

### ISSUE THREAD

**Issue by aparna1996** [s5z/zsim#155]
I am new to z-sim. I was running the het.cfg test and faced the following error. 
```
/build/parsec/blackscholes/blackscholes : No such file or directory
/build/speccpu2006/401.bzip2/401.bzip2 : No such file or directory
```

I am using z-sim with pin tool version pin-2.14-71313 using the changes suggested in https://github.com/s5z/zsim/pull/149/files. Is there any specific way that I have to build the tool to get the benchmarks or do I have to install them separately myself? I tried to install it myself and found that speccpu2006 is a paid benchmark.

**Comment by nrodia** [comment]
As far as I know, these benchmarks are not included with zsim. If you'd like to run them on zsim, you will have to download/purchase and install them yourself. 

If you want to try out the heterogeneous config (het.cfg), you can sub in applications of your choice for the "command = " parameters under process0 and process1.

**Comment by aparna1996** [comment]
I have installed the PARSEC benchmark suite. But, I have not been able to run the applications using the parsecmgmt tool inside zsim.

So, do I need to type the whole command i.e.,
`/home/aparna/Downloads/Software/zsim-master/parsec-benchmark-master/pkgs/apps/blackscholes/inst/amd64-linux.gcc/bin/blackscholes 4 /home/aparna/Downloads/Software/zsim-master/parsec-benchmark-master/pkgs/apps/blackscholes/inputs/in_4.txt /home/aparna/Downloads/Software/zsim-master/parsec-benchmark-master/pkgs/apps/blackscholes/output`

or is the option of using parsecmgmt available?

When I tried using `/home/aparna/Downloads/Software/zsim-master/parsec-benchmark-master/bin/parsecmgmt -a run -p blackscholes`, I got the following error.

`[S 0] WARN: [0] ContextChange, reason SIGRETURN, inSyscall 1
/home/aparna/Downloads/Software/zsim-master/parsec-benchmark-master/bin/parsecmgmt: eval: line 117: syntax error near unexpected token ('
/home/aparna/Downloads/Software/zsim-master/parsec-benchmark-master/bin/parsecmgmt: eval: line 117: parsecdir=[S 2F] Created child process 3 on the fly, inheriting 2's config [S 2F] Thread 0 forking, child procIdx=3 [S 3F] Forked child (tid 0/0), PID 2535, parent PID 2533 [S 3F] Thread 0 starting [S 3F] FF control Thread TID 2536 [S 2F] Following exec(): dirname [S 3F] Time slice ended, context-switched 1 threads, runQueue size 0, available 0 [S 3F] State: 196608r [S 3F] Created child process 4 on the fly, inheriting 3's config [S 3F] Thread 0 forking, child procIdx=4 [S 4F] Forked child (tid 0/0), PID 2537, parent PID 2535 [S 4F] Thread 0 starting [S 4F] FF control Thread TID 2538 [S 4F] Following exec(): dirname /home/aparna/Downloads/Software/zsim-master/parsec-benchmark-master/bin/parsecmgmt [S 4] Started instance [S 4] Started process, PID 2539 [S 4] procMask: 0x1000000000000000 [S 4] [sched] Cleaned up pid 4, 1 tids [S 4] vDSO info initialized [S 4] Thread 0 starting /home/aparna/Downloads/Software/zsim-master/parsec-benchmark-master/bin [S 3F] Thread 0 finished [S 3F] Finished, code 0 [S 2] Started instance [S 2] Started process, PID 2541 [S 2] procMask: 0x800000000000000 [S 2] [sched] Cleaned up pid 2, 1 tids [S 2] vDSO info initialized [S 2] Thread 0 starting . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 0 . . . . . . . . . . . . . . . . . . . . . . /home/aparna/Downloads/Software/zsim-master/parsec-benchmark-master/bin . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . /home/aparna/Downloads/Software/zsim-master/parsec-benchmark-master . . . . . . . . . .'
[PARSEC] Error: Unable to autodetect path to the PARSEC benchmark suite. Either define an environment variable PARSECDIR, or edit  and set PARSECDIR to the correct value at the beginning of the file.
[S 0] Thread 0 finished
[S 0] Finished, code 1
[S 0] Dumping termination stats
[S 0] Finished scheduler watchdog thread
[H] Child 2517 done
[H] All children done, exiting
`

**Comment by hlitz** [comment]
Don't use parsecmgt run the individual application binaries

**Comment by aparna1996** [comment]
Okay. Do you have any idea why does parsecmgmt does not work in zsim?

**Comment by Amin-Azar** [comment]
These management scripts does many operations like, compile copy inputs etc other than running the benchmark. Aside from if it is doable vai a pintool, you need to think if it's a right thing to do ?! Probably not if you are measuring something per each benchmark!

If you haven't' figure out the commands to run each benchmark, take a look at this link for command line arguments:
https://github.com/Amin1360/rasd

You need to pass these as Command="xxx" in your process0 field in the scripts.
