### ISSUE TITLE
Simulating Zcache

### ISSUE THREAD

**Issue by aparna1996** [s5z/zsim#156]
Hi,

I want to attempt implementing [zcache](https://people.csail.mit.edu/sanchez/papers/2010.zcache.micro.pdf) in z-sim. Has anyone done this before?

How do I go about changing the cache architecture of zsim? 
I am new to z-sim and have run the basic tests. Which all files do I have to change in order to change the cache architecture? How interdependent are the files?

**Comment by gaomy3832** [comment]
It is already here, isn't it?

https://github.com/s5z/zsim/blob/master/src/cache_arrays.h#L77
https://github.com/s5z/zsim/blob/master/tests/pgo.cfg#L50
