### ISSUE TITLE
Handling Syscalls

### ISSUE THREAD

**Issue by ShehabElsayed** [s5z/zsim#160]
I am just confused about the way Zsim handles syscalls. So as far as I understand PIN is used to detect syscalls and handles them through the SyscallEnter and SyscallExit functions. But doesn't this mean that syscalls are executed when the actual thread (the one running on the host machine) reaches this point in the execution and NOT when the simulated thread (the one Zsim simulates to be running on the provided configuration) reaches that point ???!!!!

For example, when a thread reaches a blocking syscall it is removed from the cores map (the threadID to core map), but it the simulated thread might actually still be running.

Is my understanding correct or am I missing something??

**Comment by hlitz** [comment]
You are right but I don't think it is an issue. Zsim simulates based on basic blocks which are usually around 10 instructions so this means you are not losing much accuracy by not simulating syscalls precisely on the per instruction basis.

**Comment by ShehabElsayed** [comment]
Thank you very much for your reply. But I think if I wanted to get the time (cycle count) of the core at which it arrives at this syscall I have to add it as an event in the contention phase since as far as I understand a weave phase can span multiple basic blocks. Is my understanding correct?

**Comment by gaomy3832** [comment]
As @hlitz pointed out, the actual thread (the one runs the modified binary) and the simulated thread (the one runs the inserted Pintool functions, i.e., zsim callbacks) will at most differ by the length of a basic block, i.e., 10s of instructions, and thus the corresponding time error may also be 10s of cycles, which is minor. Actually, I guess the callbacks might be executed by the same thread of the app thread.

If you are talking about weave phase, there are already events created when a thread joins/leaves a core. Take a look at `CoreRecorder::notifyJoin()` and `CoreRecorder::notifyLeave()`. These events will ensure the thread finishes all the pending events in the weave phase, and adjusts the corresponding time info before actually leave.

**Comment by hlitz** [comment]
I think he is concerned about contention events that happened before the syscall but which are only simulated at the end of the phase (weave).

**Comment by ShehabElsayed** [comment]
Thanks a lot for the very useful feedback. I think I managed to get what I was looking for.
