### ISSUE TITLE
Pass arguments to magic operations

### ISSUE THREAD

**Issue by ShehabElsayed** [s5z/zsim#163]
Is there a way to pass arguments to magic operations or do they have to be embedded in the value of the rcx register used in the xchg instruction?

**Comment by benpatsai** [comment]
Here's a simple way to pass arguments in your program to zsim by using the context:

`#define zsim_my_magic_op(arg1, arg2)   __asm__ __volatile__("xchg %%rcx, %%rcx;"  : : "S"(arg1), "d"(arg2), "c"(ZSIM_MAGIC_OP_MY_OP)  : "memory");`                                                               

And in your simulator, you will use PIN_GetContextReg to get your arguments, for example:

`auto arg1 = PIN_GetContextReg(ctxt, REG_RSI);`
`auto arg2 = PIN_GetContextReg(ctxt, REG_RDX);`

**Comment by ShehabElsayed** [comment]
This looks interesting. I will give it a try. Thank you very much
