### ISSUE TITLE
How to print stats at certian events (for example at certain magic operations)

### ISSUE THREAD

**Issue by ShehabElsayed** [s5z/zsim#164]
Is there a way to print stats when certain magic operations are met? I have tried creating a new stats set similar to the periodic stats but they dump when the magic operation happens. However, I am running into an assertion failure in the ProcessStats::updateCore function. I think one reason could be is that this magic operation would happen in the middle of the phase and so some cores might not have updated their stats yet (Cycles and Insts). Is this correct? If yes, is there a way to overcome this problem?

Thank you very much in advance

**Comment by benpatsai** [comment]
If printing stats in the middle a phase is the problem, you can create a "StatsDumpEvent" which has a callback() to dump the stats and insert it into the global event queue (zinfo->eventQueue). Since those events always fire up at the end of a phase, you will not have that problem. 

Hope this helps.

**Comment by ShehabElsayed** [comment]
Thanks a lot for the reply. But if I create a StatsDumpEvent that is added to the global event queue (similar to the way Periodic Stats work) the stats being printed will be those at the end of the phase not at the moment the event (magic operation) happened. Is my understanding correct?

**Comment by benpatsai** [comment]
That's correct, but if your phase length is reasonably short (e.g. 10000 cycles as the default), the number should not off by too much. However, if you expect this magic op happens very frequently, then this trick will not work.

**Comment by ShehabElsayed** [comment]
Yeah, I think this is a problem I might run into since I expect some of the magic operations to be relatively frequent. I also tried to shorten the phase length but I the least I could get running is 1000 cycles (with the original code without (almost) any of my modifications), otherwise it runs in the assertion failure I mentioned in my original post.

**Comment by abhishekk06** [comment]
Hi,

Can this be explained a little bit more? I actually want to implement some magic operation so that I can have control from the application level on the performance measure (both core and memory(cache)).
