### ISSUE TITLE
Cache hierarchy writeback policy and coherency transient states

### ISSUE THREAD

**Issue by ShehabElsayed** [s5z/zsim#167]
I am a little confused about the cache hierarchies supported and coherency protocol implementation in Zsim. As far as I understand, By default, Zsim supports inclusive cache hierarchies with some support for exclusive caches via the "nonInclusiveHack" (as explained in https://github.com/s5z/zsim/issues/62). However, I am not sure whether write-through or write-back policy is implemented. For write-through then I expected the L1 to update the L2 on every GETX hit. And for write-back, I expect the L2 to be able to forward some requests to the owner L1. However, I couldn't find out how either of these 2 cases is implemented?

Also,, I could only find cases for the stable states of MESI protocol. What about the transient states?

Thanks in advance

**Comment by nrodia** [comment]
Zsim uses a write-back policy for the caches. See the AccessType enum in memory_hierarchy.h, where PUTS and PUTX distinguish between clean and dirty writebacks, respectively.

Could you explain what you mean by transient states of the MESI protocol?

**Comment by ShehabElsayed** [comment]
Thanks for your reply. I meant the state a block goes into when going from one steady state to another. For example, when going from M to S a block goes through a transient state where it could still forward data to requestors until it gets the writeback Ack for the next memory level. However, I later understood that these aren't modeled in Zsim. But thanks for your reply.
