### ISSUE TITLE
Trace Driven Simulation. About skew & retrace & terminal

### ISSUE THREAD

**Issue by zinechant** [s5z/zsim#176]
Hi all,
I am new to ZSim. Thanks for your great work.
I am trying to replay a memory trace(which was from an accelerator that uses local memory only without any cache hierarchy) just on the memory subsystem to understand the data locality and the benefits it could possibly get from the cache hierarchy. I guess I would set TraceDriven=true for the simulation and supply the trace file. But there are several things not so clear to me.

1. How do I parse my trace file to the required format? I think I may write a program that calls AccessTraceWriter class. Is this the right way to do it?
2. The trace file was from a simulator of the accelerator, the latency and cycle of the request are both inaccurate for the cache system. If I turn on the useSkews setting and provide the retrace file path. Does it mean that the cache would ignore the cycle of the request in the trace and generate the new trace using the actual possible request cycle which could be calculated considering the previous requests and the cache latency settings?
3. This question is not about TraceDriven simulation. I am aware that TracingCache can be used to dump trace. But it seems that terminal cache can't be of type 'Tracing'. So, how to dump the trace for l1i, l1d?

Thanks in advance.

Regards,
Chen

**Comment by satanu01** [comment]
have you find that solution for trace file?

**Comment by zinechant** [comment]
I don't exactly remember. But I think AccessTraceWriter is the correct way to go.
If you don't have any other dependency, I would suggest you go for Gem5 for better documentation/community/support/extensibility, as paid ARM engineers are behind it.
