### ISSUE TITLE
Channel bandwidth modeling in ddr_mem?

### ISSUE THREAD

**Issue by jangjae** [s5z/zsim#190]
Is there any channel bandwidth modeling in ddr_mem?
At first glance, It seems that there is only static latency of controller access (controllerSysLatency), but no timing or contention model for channel bandwidth.
If so, is it feasible to insert additional layer between memSplitter and DDRMemory to estimate BW (e.g. using MD1 model)?
Also, I'm curious about how to set reasonable number for controllerSysLatency, or if there is any reference to that number.

Thanks in advance,
Jaey

**Comment by gaomy3832** [comment]
DDRMemory models the details of DDR memory, including the bandwidth. The effective latency and bandwidth are both determined by the timing parameters. For example, the theoretical peak bandwidth for one channel is 64 bits / (tCK / 2). For the default DDR3-1333, tCK = 1.5 ns, so bandwidth = 85.33 Gb/s = 10.67 GB/s. You should learn the meanings of the timing parameters to understand DDR memory.

**Comment by jangjae** [comment]
Okay, I missed its event based behavior in weave-phase functionality.
Thank you.
