### ISSUE TITLE
libhdf5 ver 1.8 compile issues

### ISSUE THREAD

**Issue by hlitz** [s5z/zsim#21]
Latest zsim fails to compile with libhdf1.8. To fix add "-DH5_USE_16_API" to SConstruct.

diff --git a/SConstruct b/SConstruct
index b2d4fff..7fc2586 100644
--- a/SConstruct
+++ b/SConstruct
@@ -46,7 +46,7 @@ def buildSim(cppFlags, dir, type, pgo=None):
     # NOTE (dsm 10 Jan 2013): Tested with Pin 2.10 thru 2.12 as well
     # NOTE: Original Pin flags included -fno-strict-aliasing, but zsim does not do type punning
     env["CPPFLAGS"] += " -g -std=c++0x -Wall -Wno-unknown-pragmas -fomit-frame-pointer -fno-stack-protector"
-    env["CPPFLAGS"] += " -MMD -DBIGARRAY_MULTIPLIER=1 -DUSING_XED -DTARGET_IA32E -DHOST_IA32E -fPIC -DTARGET_LINUX"
+    env["CPPFLAGS"] += " -MMD -DBIGARRAY_MULTIPLIER=1 -DUSING_XED -DTARGET_IA32E -DHOST_IA32E -fPIC -DTARGET_LINUX -DH5_USE_16_API "

     # Pin 2.12+ kits have changed the layout of includes, detect whether we need
     # source/include/ or source/include/pin/

**Comment by s5z** [comment]
Yeah, it was broken on 14.10 too. 748aad33 should fix this. If it still does not work, please reopen.
