### ISSUE TITLE
Assertion error when prefetcher is enabled

### ISSUE THREAD

**Issue by Subisha** [s5z/zsim#216]
I'm simulating ZSIM with DramSim. Simulation terminates with the following error when prefetcher is enabled.

Failed assertion on build/opt/core_recorder.cpp:123 'startCycle >= prevRespCycle' (with '1004 >= 1005')
[S 0] [0] Internal exception detected:
[S 0] [0]  Code: 1
[S 0] [0]  Address: 0x7ffff63ee557
[S 0] [0]  Description: Exception Code: ACCESS_INVALID_ADDRESS. Exception Address = 0x7ffff63ee557. Access Type: UNKNOWN. Access Address = 0x000000000
[S 0] [0]  Caused by invalid access to address 0x0
[S 0] [0] Backtrace (9/40 max frames)
[S 0] [0]  /home/subisha/Desktop/Simulator/zsim/build/opt/zsim.cpp:1392 / InternalExceptionHandler
[S 0] [0]  :? / LEVEL_PINCLIENT::IEH_CALLBACKS::NotifyInternalException(unsigned int, LEVEL_BASE::EXCEPTION_INFO*, LEVEL_VM::CONTEXT*)
[S 0] [0]  /home/subisha/Desktop/Simulator/zsim/dependencies/pin-2.14-71313-gcc.4.4.7-linux/intel64/bin/pinbin(_ZN8LEVEL_VM12SIGNALS_IMPL19InternalHandlerSyncEiPN7BARECRT8SIGXINFOEPN5PINVM11ISIGCONTEXTEPPKNS_14SCT_ATTRIBUTESEPNS_5PCTXTEPj+0x444) [0x3043a9454]
[S 0] [0]  /home/subisha/Desktop/Simulator/zsim/dependencies/pin-2.14-71313-gcc.4.4.7-linux/intel64/bin/pinbin(_ZN8LEVEL_VM12SIGNALS_IMPL20HandlePhysicalSignalEPN7BARECRT8SIGXINFOEPN5PINVM11ISIGCONTEXTE+0x124) [0x3043aa1f4]
[S 0] [0]  /home/subisha/Desktop/Simulator/zsim/dependencies/pin-2.14-71313-gcc.4.4.7-linux/intel64/bin/pinbin(_ZN5PINVM28SIGNAL_DETAILS_LINUX_INTEL6415InternalHandlerEiPN7BARECRT8SIGXINFOEPv+0xe8) [0x304438c88]
[S 0] [0]  /home/subisha/Desktop/Simulator/zsim/dependencies/pin-2.14-71313-gcc.4.4.7-linux/intel64/bin/pinbin(BARECRT_SigReturnRt+0) [0x30446603c]
[S 0] [0]  /home/subisha/Desktop/Simulator/zsim/build/opt/timing_event.h:107 / TimingEvent::addChild(TimingEvent*, EventRecorder*)
[S 0] [0]  /home/subisha/Desktop/Simulator/zsim/build/opt/core_recorder.h:78 / CoreRecorder::record(unsigned long)
[S 0] [0]  [0x7fffe3a22d47]
C: Tool (or Pin) caused signal 11 at PC 0x7ffff63ee557
Pin app terminated abnormally due to signal 11.
[H] Child1 3136 done
[H] exit code :139
[H] Panic on build/opt/zsim_harness.cpp:124: Child 3136 (idx 0) exit was anomalous, killing simulation
[H] WARN: Hard death at exit (1 children running), killing the whole process tree

**Comment by gaomy3832** [comment]
See #34

**Comment by Subisha** [comment]
Thanks. That solved the issue.
