### ISSUE TITLE
compilation error due to hdf5-1.8.4

### ISSUE THREAD

**Issue by lkartik** [s5z/zsim#22]
I am new to zsim and may be asking a simple doubt. I tried to install the simulator in my system with ubuntu 12.04,Pin 2.12 ,Intel Corei5. I followed the instructions in README.md file.
I tried installing hdf5 in 2 ways:
1st way)I installed hdf5 from below link(through software manager) and I have pasted below the error:
link : http://packages.ubuntu.com/lucid/science/hdf5-tools through software center
natarajan@ubuntu:~/zsim$ sudo scons -j16
build/opt/access_tracing.cpp:28:18: fatal error: hdf5.h: No such file or directory
compilation terminated.
build/opt/access_tracing.cpp:28:18: fatal error: hdf5.h: No such file or directory
compilation terminated.
build/opt/hdf5_stats.cpp:29:18: fatal error: hdf5.h: No such file or directory
compilation terminated.
echo "#define ZSIM_BUILDDATE \""`date`\""\n#define ZSIM_BUILDVERSION \""`python misc/gitver.py`\""" >>build/opt/version.h
scons: **\* [build/opt/access_tracing.os] Error 1
scons: **\* [build/opt/access_tracing.ot] Error 1
scons: **\* [build/opt/hdf5_stats.os] Error 1
scons: building terminated because of errors.

I wonder why it cannot locate the path of hdf5.h because I am able to locate it?
natarajan@ubuntu:~$ locate hdf5.h
/home/natarajan/hdf5-1.8.4/src/hdf5.h
/home/natarajan/hdf5-1.8.4/test/testhdf5.h
/home/natarajan/hdf5-1.8.4/testpar/testphdf5.h
/usr/local/hdf5/include/hdf5.h

2nd way) I tried to install hdf5 from source website and followed the instructions from following link.
link:http://www.hdfgroup.org/ftp/HDF5/current/src/unpacked/release_docs/INSTALL
 and modified the path for hdf5.h and hdf5_hl.h in hdf5_stats.cpp and access_tracing.cpp, 

I get the following error:
build/opt/access_tracing.cpp:138:101: error: too few arguments to function ‘hid_t H5Acreate2(hid_t, const char_, hid_t, hid_t, hid_t, hid_t)’
/home/natarajan/hdf5-1.8.4/src/H5Apublic.h:44:16: note: declared here
build/opt/access_tracing.cpp:142:97: error: too few arguments to function ‘hid_t H5Acreate2(hid_t, const char_, hid_t, hid_t, hid_t, hid_t)’
/home/natarajan/hdf5-1.8.4/src/H5Apublic.h:44:16: note: declared here
build/opt/access_tracing.cpp: In constructor ‘AccessTraceWriter::AccessTraceWriter(g_string, uint32_t)’:
build/opt/access_tracing.cpp:138:101: error: too few arguments to function ‘hid_t H5Acreate2(hid_t, const char_, hid_t, hid_t, hid_t, hid_t)’
/home/natarajan/hdf5-1.8.4/src/H5Apublic.h:44:16: note: declared here
build/opt/access_tracing.cpp:142:97: error: too few arguments to function ‘hid_t H5Acreate2(hid_t, const char_, hid_t, hid_t, hid_t, hid_t)’
/home/natarajan/hdf5-1.8.4/src/H5Apublic.h:44:16: note: declared here
echo "#define ZSIM_BUILDDATE \""`date`\""\n#define ZSIM_BUILDVERSION \""`python misc/gitver.py`\""" >>build/opt/version.h
scons: **\* [build/opt/access_tracing.os] Error 1
scons: **\* [build/opt/access_tracing.ot] Error 1
scons: building terminated because of errors.

Could anyone please help me with these errors?

**Comment by AbhishekUoR** [comment]
@lkartik I did not understand the README part and has same problem on the machine, can u explain how to solve this problem?
