### ISSUE TITLE
how to enable hardware prefetcher

### ISSUE THREAD

**Issue by shuzihua** [s5z/zsim#23]
I have been using zsim for a while, thank you for this amazing simulator!
Currently I want to use the hardware prefetcher, but I do not  know how to enable it, could you please give me some advise?

For example, if I want to add a prefetcher for L2 cahce, should I set L2 as the parent of the prefetcher, or should I set the prefetcher as the parent of L2 cache? I am not quite familiar with the memory hierarchy configuration in zsim. If it is possible, could you please give me a sample cfg file?

Thank you very much.

**Comment by s5z** [comment]
You should add the prefetcher between the L1D and L2 caches to prefetch data into the L2. The following should work: 

l1d.parent = "l2prefetcher";
l2prefetcher = {
  isPrefetcher = true;
  parent = "l2";
};

**Comment by shuzihua** [comment]
Thank you very much! Is that means that the prefetcher can not prefetch accoding to both L1D and L1I misses? Because I found that the prefetcher can only have one child.

**Comment by s5z** [comment]
That's correct, the prefetcher will only look at the L1D access stream. Instruction prefetchers are typically quite different from the streaming prefetcher that zsim includes, but you could prefetch according to L1I misses by introducing another prefetcher between the L1I and L2.

**Comment by shuzihua** [comment]
Thanks.
