### ISSUE TITLE
running spec06 on zsim

### ISSUE THREAD

**Issue by zhuguoliang** [s5z/zsim#24]
Hi community!
I am simulating using zsim but I came across the problem below.
[H] Starting zsim, built xxxx
[H] Removed 1 old logfiles
[H] Creating global segment, 1024 MBs
[H] Global segment shmid = 458758
[H] Pausing PIN to attach debugger, and not running deadlock detection
[H] Deadlock detection OFF
[H] Child 22741 done
[H] Panic on build/debug/zsim_harness.cpp:118: Child issued a panic, killing simulation
[H] WARN: Hard death at exit (1 children running), killing the whole process tree

My config file is as follows.

process0 = {
 command = "/home/zhuguoliang/project/mybenchmark/401/run_base_ref_gcc43-64bit.0000/bzip2_base.gcc43-64bit /home/zhuguoliang/project/mybenchmark/401/run_base_ref_gcc43-64bit.0000/input.source 200";
};

It is my first time using zsim. Please give me a hit on this!

**Comment by lkartik** [comment]
Dear all,
I have an error which may be trivial for all, but I am new to zsim. I have to run a sample Helloworld application in ZSim. 
I followed the issue no.3 and then added 1) sim.perProcessDir=True 2) copied hello.c and its object file into a subdirectory p0 in zsim main directory. 
sim = {
    phaseLength = 10000;
    statsPhaseInterval = 1000;
    perProcessDir = true;//added this line after reading issue no.3: https://github.com/s5z/zsim/issues/3
    maxMinInstrs = 50000000L;

    // attachDebugger = True;
}

process0 = {
    command = "/home/natarajan/zsim/p0/a.out"; //   
	foldername = "p0"; //copied my hello.c and its object file to p0 directory after reading issue no.3: https://github.com/s5z/zsim/issues/3 
 };

I receive an empty zsim.out file with the following messages on the command line:
[H] Starting zsim, built Wed Jan 7 18:20:22 EST 2015 (rev master:35:912253f:2fc 29+ 9- da454661)
[H] Creating global segment, 1024 MBs
[H] Global segment shmid = 1540107
[H] Running each process in a different subdirectory
[H] Deadlock detection ON
[S 0] Started instance
[S 0] Limiting concurrent threads to 8
[S 0] Started RR scheduler, quantum=10000 phases
[S 0] mem-0: domain 0, 4 ranks/ch 8 banks/rank, tech DDR3-1066-CL8, boundLat 64 rd / 10 wr
[S 0] mem-0: Address mapping rank:col:bank row 63:15 col 12:3 rank 14:13 bank 2:0
[S 0] mem-1: domain 0, 4 ranks/ch 8 banks/rank, tech DDR3-1066-CL8, boundLat 64 rd / 10 wr
[S 0] mem-1: Address mapping rank:col:bank row 63:15 col 12:3 rank 14:13 bank 2:0
[S 0] mem-2: domain 0, 4 ranks/ch 8 banks/rank, tech DDR3-1066-CL8, boundLat 64 rd / 10 wr
[S 0] mem-2: Address mapping rank:col:bank row 63:15 col 12:3 rank 14:13 bank 2:0
[S 0] mem-3: domain 0, 4 ranks/ch 8 banks/rank, tech DDR3-1066-CL8, boundLat 64 rd / 10 wr
[S 0] mem-3: Address mapping rank:col:bank row 63:15 col 12:3 rank 14:13 bank 2:0
[S 0] l2_beefy's children are all terminal OR PREFETCHERS, interleaving them
[S 0] Initialized system
[S 0] HDF5 backend: Opening /home/natarajan/zsim/zsim.h5
[S 0] HDF5 backend: Created table, 10552 bytes/record, 100 records/write
[S 0] HDF5 backend: Opening /home/natarajan/zsim/zsim-ev.h5
[S 0] HDF5 backend: Created table, 10552 bytes/record, 13 records/write
[S 0] WARN: maxMinInstrs IS DEPRECATED
[S 0] HDF5 backend: Opening /home/natarajan/zsim/zsim-cmp.h5
[S 0] HDF5 backend: Created table, 3488 bytes/record, 1 records/write
[S 0] WARN: Setting process0.foldername not used during configuration
[S 0] Panic on build/opt/config.cpp:126: 1 setting not used during configuration
[H] Child 5101 done
[H] Panic on build/opt/zsim_harness.cpp:118: Child issued a panic, killing simulation

May I know what is the process.command for running a basic (cc hello.c , ./a.out ) helloworld application?
I don't see any object file generated when I run scons -j16 for hello.c in p0 subdirectory(zsim/p0/) eventhough I have given sim.PerProcessDir=true?

**Comment by hlitz** [comment]
zsim tells you what the problem is: [S 0] Panic on 
build/opt/config.cpp:126: 1 setting not used during configuration

You are using a config string that is unknown by zsim, probably the line 
"     = 50000000L; "

**Comment by zhuguoliang** [comment]
Hi lkartik and hlitz . I fixed my issue. I changed the attachDebugger back to false. Everything works fine now. It seems that some extension of zsim doesn't support debugger very well.
However, zsim itself works with attachDebugger.

**Comment by s5z** [comment]
@zhuguoliang, glad to hear.

@lkartik, please open a new issue instead of hijacking another one. As Heiner and the output say:

[S 0] WARN: Setting process0.foldername not used during configuration

Maybe you want sim.perProcessDirs?

**Comment by lkartik** [comment]
Thanks for the help . I got it right. Sorry for asking my question here.
