### ISSUE TITLE
run with dramsim2 : ACCESS_INVALID_ADDRESS 

### ISSUE THREAD

**Issue by hftsin** [s5z/zsim#25]
When it runs with *__dramsim2__*, zsim failed with the following error outputs:

[S 0] Failed assertion on build/opt/timing_event.h:161: startCycle 130 < minStartCycle 138 (17MissResponseEvent), preDelay 0 postDelay 0 numChildren 2 str 
[S 0] [1] Internal exception detected:
[S 0] [1]  Code: 1
[S 0] [1]  Address: 0x7ffff66056a5
[S 0] [1]  Description: Exception Code: ACCESS_INVALID_ADDRESS. Exception Address = 0x7ffff66056a5. Access Type: UNKNOWN. Access Address = 0x000000000
[S 0] [1]  Caused by invalid access to address 0x0
[S 0] [1] Backtrace (11/40 max frames)
[S 0] [1]  /home/xxx/Workspace/ZSIM/zsim-src/build/opt/zsim.cpp:1417 / InternalExceptionHandler
[S 0] [1]  :? / LEVEL_PINCLIENT::IEH_CALLBACKS::NotifyInternalException(unsigned int, LEVEL_BASE::EXCEPTION_INFO*, LEVEL_VM::CONTEXT*)
[S 0] [1]  /home/xxx/Workspace/tools/pin/intel64/bin/pinbin(_ZN8LEVEL_VM12SIGNALS_IMPL19InternalHandlerSyncEiPN7BARECRT8SIGXINFOEPN5PINVM11ISIGCONTEXTEPPKNS_14SCT_ATTRIBUTESEPNS_5PCTXTEPj+0x462) [0x3077e002]
[S 0] [1]  /home/xxx/Workspace/tools/pin/intel64/bin/pinbin(_ZN8LEVEL_VM12SIGNALS_IMPL20HandlePhysicalSignalEPN7BARECRT8SIGXINFOEPN5PINVM11ISIGCONTEXTE+0x200) [0x30783c90]
[S 0] [1]  /home/xxx/Workspace/tools/pin/intel64/bin/pinbin(_ZN5PINVM28SIGNAL_DETAILS_LINUX_INTEL6415InternalHandlerEiPN7BARECRT8SIGXINFOEPv+0x9a) [0x308245ca]
[S 0] [1]  /home/xxx/Workspace/tools/pin/intel64/bin/pinbin(BARECRT_SigReturnRt+0) [0x3084fa3c]
[S 0] [1]  /home/xxx/Workspace/ZSIM/zsim-src/build/opt/timing_event.h:160 / TimingEvent::run(unsigned long)
[S 0] [1]  /home/xxx/Workspace/ZSIM/zsim-src/build/opt/contention_sim.cpp:309 / ContentionSim::simulatePhaseThread(unsigned int)
[S 0] [1]  /home/xxx/Workspace/ZSIM/zsim-src/build/opt/contention_sim.cpp:282 / ContentionSim::simThreadLoop(unsigned int)
[S 0] [1]  /home/xxx/Workspace/tools/pin/intel64/bin/pinbin(_ZN8LEVEL_VM17VM_THREAD_DB_UNIX13THREAD_RUNNER9RunThreadEPN11OS_SERVICES7ITHREADE+0x291) [0x3078d8b1]
[S 0] [1]  /home/xxx/Workspace/tools/pin/intel64/bin/pinbin(_ZN11OS_SERVICES6THREAD12RootFunctionEPv+0x26) [0x3084f036]
C:Tool (or Pin) caused signal 11 at PC 0x7ffff66056a5
[H] Child 12065 done
[H] Panic on build/opt/zsim_harness.cpp:123: Child 12065 (idx 0) exit was anomalous, killing simulation

**Comment by s5z** [comment]
Set a lower minimum memory latency in the zsim configuration file. dramsim is returning a smaller latency than the minimum you specified, which is triggering this assertion.
