### ISSUE TITLE
scons -j4 error 

### ISSUE THREAD

**Issue by cyberprofali** [s5z/zsim#254]
I get the following error while in the /vagrant/ directory. 

scons: Reading SConscript files ...
Building opt zsim at build/opt
AssertionError: :
  File "/vagrant/SConstruct", line 223:
    buildSim(buildFlags[type], baseBuildDir, type)
  File "/vagrant/SConstruct", line 57:
    assert os.path.exists(joinpath(pinInclDir, "pin.H"))

**Comment by Dextershin4908** [comment]
How did you solve this problem?
