### ISSUE TITLE
types_maker.h error 

### ISSUE THREAD

**Issue by cyberprofali** [s5z/zsim#255]
I'm getting the following error after trying to build with `scons -j16` I was wondering if someone has resolved this issue? By the way I am using pin versions 3.13. Let me know thanks! 
![Screen Shot 2021-07-14 at 12 47 22 AM](https://user-images.githubusercontent.com/66300613/125569728-4b3d70c6-e9b5-4641-a230-3afaa04ff060.png)

**Comment by Aileen-Huang** [comment]
Have you solved it?I meet the same problem...

**Comment by cyberprofali** [comment]
I have not, I believe that you will have to use an older version of the pin tool but I went on to use another simulator.
