### ISSUE TITLE
Error when returning from syscall

### ISSUE THREAD

**Issue by vyoung7** [s5z/zsim#28]
Hello,

  I am trying to use zsim on a c++ file that calls a shell/system call with popen and retrieves the output.
  
  For some reason, I think zsim is not able to get the return value correctly.

  I have made a small example that shows my confusion:

// -----------------------------------------------------
// syscall_test.cpp
// -----------------------------------------------------
#include <string>
#include <iostream>
#include <stdio.h>

std::string exec(char* cmd) {
    FILE* pipe = popen(cmd, "r");
    if (!pipe) return "ERROR";
    char buffer[128];
    std::string result = "";
    while(!feof(pipe)) {
        if(fgets(buffer, 128, pipe) != NULL)
                result += buffer;
    }
    pclose(pipe);
    return result;
}

int main (void) {
    std::string ret;
    char* execstring = "echo 1234";
    ret = exec(execstring);

//    std::cout << ret;
    std::string s = "1234\n";
    if (ret.compare(s)!= 0) std::cout << "error\n";

    return 0;
}
// -----------------------------------------------------

This file executes an "echo 1234" command and checks to see if the syscall returned "1234\n".
Running it directly, there is no error as we get 1234\n.
Running it with an arbitrary pintool (say tools/SegTrace), there is no error as we get 1234\n.
However, running it with zsim gets an error. I think it is a null return?

Any idea why this is happening?

Thanks!
Vinson

**Comment by s5z** [comment]
By default, zsim prints info/warn messages to stdout/stderr, so if you use pipes the parent process will see those messages interleaved with the simulated program's output. Use sim.logToFile = true to avoid any use of stdout & stderr and preserve transparency. Does this fix the problem?

**Comment by vyoung7** [comment]
That works!
Thank you very much
