### ISSUE TITLE
request for sim configuration for multithreaded apps

### ISSUE THREAD

**Issue by lkartik** [s5z/zsim#30]
I am able to simulate Matrix Multiplication app with 2 threads in 2 in-order cores(simple.cfg). When I tried to increase the core count to 4(with 4 threads),8(with 8 threads),etc , I do see that only 2 cores(2 threads executed simultaneously,one in each core) are used and there is context switch between the 2 threads and other threads are idle. I don't know/understand what is the exact scheduler configuration for "number of  domains, contention threads and  parallelism" for scheduling N threads to N cores and execute them simultaneously without context switch. Any help would be greatly appreciated

**Comment by s5z** [comment]
See tests/het.cfg for a configuration with more cores. I think you're not changing the number of cores. Also see init.cpp to understand how each parameter is used (sim.* params do not affect the number of cores; sys.* has to do with system config).

**Comment by lkartik** [comment]
Thanks for the reply. I edited the het.cfg and got the required number of simple cores and threads. Previously I had changed the number of cores, but I did use the edited out.cfg of my previous simulations which might be the reason. .out.cfg has the format of "cores :{ simpleCore :{" instead of "cores ={ simpleCore = {" which is the format of "tests/*.cfg"
