### ISSUE TITLE
Understanding WayPart configuration for multicores

### ISSUE THREAD

**Issue by lkartik** [s5z/zsim#31]
I tried to run a 16-threaded matrix multiplication application with UCP(shared 16-way set-associative L3) on default het.cfg(16 cores). I only changed the replacement policy as sys.caches.l3.repl.type="WayPart". I did not specify umonWays and umonLines.
I got an error message: 
[S 0] Failed assertion on build/opt/part_repl_policies.h:234 'curWay == ways' (with '97 == 16')
For a 32-way set associative L3:
~/zsim/build/opt/zsim.cpp:1393 / InternalExceptionHandler
For a 64way set-associative L3,
 [S 0] Failed assertion on build/opt/part_repl_policies.h:234 'curWay == ways'  (with '152 == 64')

By reading init.cpp ,
ways=Buckets (for 16way L3 , so 16 buckets)
Is umonWays , the sampled number of UMON DSS ways? (umonWays=ways-> 16ways here)
Is umonLines, the sampled number of UMON DSS lines (umonWays x associativity,) ? which by default is 256(assuming 16 sets are sampled for a 16-way cache)?
May I get a sample UCP configuration please ?

**Comment by s5z** [comment]
umonWays is the number of ways in the monitor. umonSets = umonLines / umonWays. The associativity of the real cache is not used in building the umon, the umon is configured independently. If you use fewer umonWays than real ways, the lookahead code will interpolate the miss curve.
