### ISSUE TITLE
Running the ZSim debugger / running ZSim with gdb

### ISSUE THREAD

**Issue by kartikram3** [s5z/zsim#32]
I compiled zsim in debug mode using "scons --d". Then I naively ran "gdb ./build/opt/zsim " from the zsim home folder and then "run ./tests/simple.cfg" from inside gdb's interface. It seems to run correctly. However, when I run "info functions" inside gdb, I cannot obtain many of zsim's functions, specifically all the functions that are inside the libzsim.so shared library. 

I did set sim.attachDebugger to true in the config file but that did not seem to make a difference to gdb.

**Comment by gaomy3832** [comment]
My experience is that as long as you set sim.attachDebugger to true, zsim will be attached to gdb automatically. You can just start zsim normally without gdb, and then a gdb window will pop out. If you are using ssh, make sure you have X forwarding.

**Comment by kartikram3** [comment]
Thanks, that solves it ! I did not have forwarding setup as I assumed that gdb would run inside the terminal.

**Comment by dhiraj113** [comment]
Is debugging from the popped out gdb xterms the best that could done or is it somehow possible to get an IDE instead of the gdb xterm to attach to the forked out processes?

**Comment by qianlong-zhang** [comment]
Hi all, when I do as @gaomy3832 said, my zsim hang, no window pop out, I use printf find zsim hang in sleep(1) function in notifyHarnessForDebugger(), does anyone get that error? thanks

**Comment by abhishekk06** [comment]
Hi,

I am having a hard time debugging zsim. Attach debugger doesn't work for me. For some reason, it pops up an UI a bit too late (no clue why). Also, gdb doesn't show all the modules (especially filter array and etc). Any help is much appreciated.

**Comment by qishao-chalmers** [comment]
> Hi,
> 
> I am having a hard time debugging zsim. Attach debugger doesn't work for me. For some reason, it pops up an UI a bit too late (no clue why). Also, gdb doesn't show all the modules (especially filter array and etc). Any help is much appreciated.

Hi, I meet the same issue. But even the UI does not pop out after I set sim.attachDebugger as true... Did you find the way to solve it? Thanks for your help.
