### ISSUE TITLE
ZSim prefetcher correctness

### ISSUE THREAD

**Issue by kartikram3** [s5z/zsim#33]
There is the following code in the prefetch.h.

As seen in the code, if we have an entry miss, then we set candScore to -1. Then we check if the array[i].ts (timestamp) is less than candScore for each element of the array, asuming that our current access is not more than 500 cyles after the previous access.
However, array[i].ts is always positive, because it is a timestamp, which cannot be negative. Therefore, it seems like the "if" check( on line 12 of the code below) always fails. In this case, we might never be able to set an LRU candidate to replace in array, in case of an entry miss.

Would appreciate any comments on this, in case I am not seeing this correctly.

 if (idx == 16) { // entry miss
uint32_t cand = 16;
uint64_t candScore = -1;
//uint64_t candScore = 0;
for (uint32_t i = 0; i < 16; i++) {
if (array[i].lastCycle > reqCycle + 500) continue; // warm prefetches, not even a candidate
/*uint64_t score = (reqCycle - array[i].lastCycle)*(3 - array[i].conf.counter());
if (score > candScore) {
cand = i;
candScore = score;
}*/
if (array[i].ts < candScore) { // just LRU 
cand = i;
candScore = array[i].ts;
}
}
if (cand < 16) {
idx = cand;
array[idx].alloc(reqCycle);
array[idx].lastPos = pos;
array[idx].ts = timestamp++;
tag[idx] = pageAddr;
}
DBG("%s: MISS alloc idx %d", name.c_str(), idx);
}

**Comment by s5z** [comment]
candScore is also unsigned, so -1 == UINT64_MAX and the first comparison always succeeds.
