### ISSUE TITLE
Understanding the different kinds of cache

### ISSUE THREAD

**Issue by kartikram3** [s5z/zsim#36]
I have a query about what the different kinds of cache mean.
There are the following types currently available in zsim : 

1. Simple
2. Timing

 There is also the filter cache for L1, but that seems to be more of a code optimization thing, rather than a real cache in the memory hierarchy.

I noticed that the timing cache has significant more details than the simple cache eg : It has MSHRs, and more event recordings. So it seems to be a better cache model than simple cache. However, I also noticed that the "Simple" cache was used for the pgo.cfg, which was used in the zsim paper.  

Additionally, timing cache gave assertion failure at line 279 of ooo_core_recorder.cpp at one of my config files, which leads me to suspect that it does not support weave models.

So I am a bit confused about when each kind of cache should be used. Is simple cache the correct one to use for most simulations, and timing cache for only certain kinds of configurations that do not use the weave models ?

**Comment by s5z** [comment]
The typical configuration is to use Simple for the private caches (L1s, L2s) and Timing for the shared cache. L1s should not be Timing. We've barely tested multiple levels of Timing cache (e.g. L3s and L2s), it should work but I wouldn't be surprised if it failed. If so, please post a minimal config and testcase that reproduces the bug.
