### ISSUE TITLE
Cannot resolve 'gm_create failed shmget: Invalid argument'

### ISSUE THREAD

**Issue by vkalp** [s5z/zsim#38]
I recently installed zsim on  Ubuntu 12.04.5 LTS @ Intel i7 and when trying to launch a test run  (./build/opt/zsim tests/simple.cfg) I am getting 'gm_create failed shmget: Invalid argument'.

I read Memory Management section in  README.md and as far as I understood  I need to copy-replace some functions in some files. Unfortunalety, I cannot figure out what to change and where, thus I would like to ask 
- which files should be changed (including their relative locations) and
- what changes should be done (i. e. I would like  to get some examples of these changes).

Side note: there is no g_stl folder, mentioned in Memory Management section, in my zsim installation.

**Comment by hlitz** [comment]
I had this problem once and this solved it:
http://stackoverflow.com/questions/16630261/creating-my-first-unix-server-client-but-getting-a-shmget-invalid-argument-er

**Comment by s5z** [comment]
You need to update your distribution's kernel.shm* values. See the README.

**Comment by AbhishekUoR** [comment]
The README does not provide any instruction on updating the value

**Comment by AbhishekUoR** [comment]
The correct way is to use this command 
sudo sh -c 'echo 1073741824> /proc/sys/kernel/shmmax'
