### ISSUE TITLE
Modeling the register file ports in the OoO core

### ISSUE THREAD

**Issue by loiron** [s5z/zsim#39]
Hi,

if I understand correctly, in the OoO core, there are 3 read ports in the physical register file (RF_READS_PER_CYCLE = 3), and the the effects of the read stalls are also simulated (if (curCycleRFReads > RF_READS_PER_CYCLE) { ... ). 

But, How many write ports are there, and how are they simulated?

Thank you

**Comment by s5z** [comment]
Writes are implicitly throttled by the ROB commit bandwidth. If you're interested in modeling cores where the ROB commit bandwidth and the RF write bandwidth are mismatched (e.g., 2-wide but up to 1 RF write port), you'll have to add code for that. Note, however, that most instructions write a register, so you might bottleneck the whole pipeline on RF write bandwidth unless stores and branches are very frequent.
