### ISSUE TITLE
Is there any example configuration on DRAMSim2?

### ISSUE THREAD

**Issue by lwj0012** [s5z/zsim#40]
According to init.cpp, I insert these lines into cfg file:
    mem = {
        type = "DRAMSim";
        techIni = "ini/DDR3_micron_32M_8B_x4_sg125.ini";
        systemIni = "system.ini";
        outputDir = "zsimSPEC";
    }
But the DRAMSim seems not working...
How to set the result directory?

**Comment by lwj0012** [comment]
I did some tracing to the dramsim_mem_ctrl.cpp, find out that the tick function does not called at all?
Does the support of DRAMSim2 completed?

**Comment by lwj0012** [comment]
Problem solved...The core type must set to 'Timing' in the cfg file...

**Comment by neo921119** [comment]
Where is init.cpp? Is is in GEM5 or DRAMSim2?
