### ISSUE TITLE
Using Pinpoints with ZSim

### ISSUE THREAD

**Issue by kartikram3** [s5z/zsim#42]
I have been trying to integrate ZSim with PinPoints so that we can run simulations quickly.
https://software.intel.com/en-us/articles/pin-a-binary-instrumentation-tool-pinpoints

The pre-requisite to use Pinpoints is that the pintool (in our case libzsim.so ) should not change the 
control flow of the program in any way.

Is this the case for ZSim ? If so, I can work on doing the integration and send out a patch.
I thought I could ask this on the forum instead of reading through the entire ZSim code to 
find any modifications to the control flow, if they are indeed there.

**Comment by s5z** [comment]
That is the case with zsim, but using simpoints is already easy to do :). You can find the simpoints with the pinpoints tool, then use zsim's instruction-based fast-forwarding mode: set processX.ffiPoints to a list of instruction intervals where you'd like the program to switch between fast-forwarding and simulation modes. You can switch multiple times, eg

process0.startFastForwarded = True
process0.ffiPoints = "1000000 20000000 3000000 400000"

will fast-fwd for 1000000 instructions, simulate for 20000000, ffwd for 3000000, and so on.

**Comment by kartikram3** [comment]
Yes. Each simpoint interval seems to have a weighting though. To account for this, we may need to make some change to the code.

**Comment by s5z** [comment]
Not necessarily: you can dump the stats on every switch from non-ff to ff, and then weight each sample appropriately in the scripts. I don't see how you could add weighting to the simulator itself.
