### ISSUE TITLE
Only one last-level cache allowed, found: [ l3 l2 l1i l1d ]

### ISSUE THREAD

**Issue by yarcod** [s5z/zsim#43]
I have recently gotten this error message: 

Panic on build/opt/init.cpp:470: Only one last-level cache allowed, found: [ l3 l2 l1i l1d ]

Even though the configuration is exactly like the one found here: https://lagunita.stanford.edu/courses/Engineering/CS144/Introduction_to_Computer_Networking/wiki/CS316/; the only difference being the path to the program being run. This config has run just fine before, but now all of a sudden it does not.

It might be related to https://github.com/s5z/zsim/issues/37 as we recently updated to a new kernel here as well. 

What can I do? 

Thanks!

**Comment by s5z** [comment]
We changed how hierarchies are specified, you now need to specify l3.children = "l2" and l2.children = "l1i|l1d". This solved a long-standing hack on whether to concatenate or interleave children caches when connecting them to parents. See the commit history for more explanation, and the new config files for  examples (mainly het.cfg)
