### ISSUE TITLE
 Deadlock issue when running MPI applications

### ISSUE THREAD

**Issue by Joyguo** [s5z/zsim#44]
I use zsim and DRAMsim2 to run mpi applications, I encounter the similar problem as #26  when I increase the number of processes (such as 36). I use het.cfg. I don't know if it is the same problem as this. I try to skip fake leave in Scheduler::syscallLeave but it doesn't help. If it is the same problem, could you help to tell me how to skip the fake leave in the SYS_futex call? Thanks for any suggestions.

[S 0] Detected possible stall due to fake leaves (4 current)
[S 0] [35/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 0] [19/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 0] [28/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 0] [4/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 0] Detected possible stall due to fake leaves (4 current)
[S 0] [27/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 0] [32/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 0] [11/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 0] [30/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 0] Detected possible stall due to fake leaves (4 current)
[S 0] [31/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 0] [11/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 0] [2/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 0] [30/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 6] Time slice ended, context-switched 16 threads, runQueue size 4, available 0
[S 6] State: 1966080r 1048576r 524288r 1245184r 1835008r 1376256r 2097152r 131072r 720896r 655360r 262144r 1441792r 393216r 1572864r 917504r 2424832r
[S 0] Terminating scheduler watchdog thread
[S 0] Delaying termination until all other processes finish
[S 0] Caught termination condition on join, exiting
[S 0] Terminating FF control thread
[H] WARN: Stalled for 20 secs so far
[H] WARN: Stalled for 30 secs so far
[H] WARN: Stalled for 40 secs so far
[H] WARN: Stalled for 50 secs so far
[H] WARN: Stalled for 60 secs so far
[H] WARN: Stalled for 70 secs so far
[H] WARN: Stalled for 80 secs so far
[H] WARN: Stalled for 90 secs so far
[H] WARN: Stalled for 100 secs so far
[H] WARN: Stalled for 110 secs so far
[H] WARN: Stalled for 120 secs so far
[H] WARN: Stalled for 130 secs so far
[H] WARN: Deadlock detected, killing children
[H] Received interrupt
[H] Attempting graceful termination
[H] Killing process 15184
[H] Done sending kill signals
[H] WARN: Hard death at exit (1 children running), killing the whole process tree
Killed

**Comment by gaomy3832** [comment]
This does not seem to be the same problem as #26 , as what I encountered was the deadlock at more than 256 threads. 36 threads seem to be a small number. Zsim has its own timeout mechanism for fake leave (2 to 4 seconds), so the fake leave stalls will be resolved one by one slowly, and eventually all of them. Only at a large number of threads will the deadlock detection 130 seconds be too short for this.

How many cores do you use in this case? I observe a context switch message in your log, so you must have fewer cores than your threads. Can you try to use more cores and see if the problem still happens?

**Comment by Joyguo** [comment]
You are right, thanks for your reply. I use 16 cores and 36 threads. The problem disappears when I increase the number of cores to 36. I am ruing a matrix multiplication application (e.g. n x n), if I increase the n to 1000, deadlock happens. What's reason do you think to cause deadlock?

[S 0] Blacklisting from future fake leaves: [8] sys_read @ 0x7fffe310331e | arg0 0x21 arg1 0x7fffe3cc3c80
[S 0] Detected possible stall due to fake leaves (1 current)
[S 0]  [13/0] sys_read (0) @ 0x7fffe310331e
[S 0] Blacklisting from future fake leaves: [13] sys_read @ 0x7fffe310331e | arg0 0x30 arg1 0x7fffe3cc3c80
[S 0] Detected possible stall due to fake leaves (1 current)
[S 0]  [16/0] sys_read (0) @ 0x7fffe310331e
[S 0] Blacklisting from future fake leaves: [16] sys_read @ 0x7fffe310331e | arg0 0x39 arg1 0x7fffe3cc3c80
[S 0] Detected possible stall due to fake leaves (1 current)
[S 0]  [15/0] sys_read (0) @ 0x7fffe310331e
[S 0] Blacklisting from future fake leaves: [15] sys_read @ 0x7fffe310331e | arg0 0x36 arg1 0x7fffe3cc3c80
[S 0] Detected possible stall due to fake leaves (1 current)
[S 0]  [17/0] sys_read (0) @ 0x7fffe310331e
[S 0] Blacklisting from future fake leaves: [17] sys_read @ 0x7fffe310331e | arg0 0x3c arg1 0x7fffe3cc3c80
[S 0] Detected possible stall due to fake leaves (1 current)
[S 0]  [14/0] sys_read (0) @ 0x7fffe310331e
[S 0] Blacklisting from future fake leaves: [14] sys_read @ 0x7fffe310331e | arg0 0x33 arg1 0x7fffe3cc3c80
[S 0] Detected possible stall due to fake leaves (3 current)
[S 0]  [12/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 0]  [8/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 0]  [11/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 0] Detected possible stall due to fake leaves (2 current)
[S 0]  [13/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 0]  [8/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 0] Detected possible stall due to fake leaves (4 current)
[S 0]  [3/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 0]  [17/0] sys_open (2) @ 0x7fffe310312e
[S 0]  [13/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 0]  [6/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 0] Detected possible stall due to fake leaves (2 current)
[S 0]  [9/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 0]  [2/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 0] Detected possible stall due to fake leaves (4 current)
[S 0]  [9/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 0]  [6/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 0]  [10/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 0]  [16/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 0] Detected possible stall due to fake leaves (1 current)
[S 0]  [8/0] sys_sched_yield (24) @ 0x7fffe30e6c05
[S 0] Blacklisting from future fake leaves: [8] sys_sched_yield @ 0x7fffe30e6c05 | arg0 0x7fffe33d5720 arg1 0xf
[S 0] Caught termination condition on syscall exit, exiting
[S 0] Delaying termination until all other processes finish
[S 0] Terminating FF control thread
[H] WARN: Stalled for 20 secs so far
[H] WARN: Stalled for 30 secs so far
[H] WARN: Stalled for 40 secs so far
[H] WARN: Stalled for 50 secs so far
[H] WARN: Stalled for 60 secs so far
[H] WARN: Stalled for 70 secs so far
[H] WARN: Stalled for 80 secs so far
[H] WARN: Stalled for 90 secs so far
[H] WARN: Stalled for 100 secs so far
[H] WARN: Stalled for 110 secs so far
[H] WARN: Stalled for 120 secs so far
[H] WARN: Stalled for 130 secs so far
[H] WARN: Deadlock detected, killing children
[H] Received interrupt
[H] Attempting graceful termination
[H] Killing process 5917
[H] Done sending kill signals
[H] WARN: Hard death at exit (1 children running), killing the whole process tree
Killed

**Comment by gaomy3832** [comment]
Look at these two log entries

> [S 0] Caught termination condition on syscall exit, exiting
> [S 0] Delaying termination until all other processes finish

That seems to mean something triggered the normal termination. Maybe your program finished successfully, or you set some termination condition (like max instr counts, etc.). But when doing cleanup it deadlocked. So I would say it seems not due to the fake leave.

**Comment by s5z** [comment]
This could be a bug that makes fake leaves fail on an overcommitted system. This line:

[S 6] Time slice ended, context-switched 16 threads, runQueue size 4, available 0

shows the scheduler is firing and switching a bunch of threads while you have a fake leave going on. We've likely never tested both at the same time, and the fake leave code is probably not expecting threads to be switched out.

This seems like a pretty obscure use case... any reason you're trying to overcommit the system with MPI processes? Note that the scheduler won't do any locality tricks (it's just round-robin), so this is unlikely to give you any decent performance if you force frequent context-switches, which seems to be what an MPI program would do.

If  you actually need overcommitted systems, I encourage you to first learn the internals of the scheduler (which you'll need to do if you're stressing it) and then submit a patch.

**Comment by Joyguo** [comment]
Hello Daniel & Mingyu, thanks for your help. Actually I have no need for overcommitting system. For last question, the termination is due to the max instruction counts. I will close this issue, thank you again.
