### ISSUE TITLE
Running GDB with zsim -- Cannot find bounds of function error

### ISSUE THREAD

**Issue by kartikram3** [s5z/zsim#47]
I get the following message while running gdb with zsim. I compiled zsim using scons --d but some debug information still seems to be missing.

It works correctly everywhere I tested except for the Indirect* functions (eg :IndirectBasicBlock, IndirectStoreSingle etc.)

![image](https://cloud.githubusercontent.com/assets/4967121/8145704/f6ca40f6-11d7-11e5-9aa2-f58329c226b9.png)

**Comment by gaomy3832** [comment]
In my understanding, IndirectBasicBlock and other similar functions are the "top" interfaces in zsim. I.e., they are the hook functions used by Pin and triggered executing when certain instruction patterns encountered. Their callers would be functions outside zsim, e.g., in Pin or the user applications. Thus gdb won't be able to track them.

I could be wrong, and I am also appreciated if someone can share a method to make the debugging more convenient.

**Comment by s5z** [comment]
I don't see any problem with this. At some point you get to Pin's dynamically generated code, which has no debugging info. But you can debug anything within libzsim.so.

**Comment by qianlong-zhang** [comment]
hi @kartikram3 I can not use gdb by set attachDebugger in zsim, which will stuck and hang in my zsim, how can you invoke the gdb?
