### ISSUE TITLE
Increase DRAMsim 2 memory latency

### ISSUE THREAD

**Issue by dzaragoza** [s5z/zsim#48]
Hello

I'm using Zsim with dramsim2. Comparing the real system to the simulation values I find that the memory latency in the simulation is smaller by about 130 cycles. I tried compensating that by increasing the latency value for memory in the mem section of the zsim config file. However, if the latency value is increased beyond a certain value, the error mentioned in issue #25 (ACCESS_INVALID_ADDRESS) occurs. 

I'm taking the DRAMsim values from the specs of the manufacturer, but it seems there is some other factor in the system adding to the latency. I would like to know how can I add more latency to memory accesses in Zsim. 

Regards

**Comment by s5z** [comment]
The memory latency for the dramsim2 controller is the bound latency, ie it's a lower bound for zsim's timing model. If you set it higher than the minimum latency that dramsim2 can return, you'll get an assertion.

If you want to add latency beyond what the specs are, you can just modify the dramsim memory controller to add a fixed latency. However, I'd recommend that you actually figure out why the discrepancy is happening. Maybe your real system is running at a higher frequency than the simulated one (remember to match sys.frequency and disable turbo/DVFS on the real system), or it uses conservative timing parameters, or closed-page mode, or the scheduler is not as good...
