### ISSUE TITLE
How to differentiate memory controllers?

### ISSUE THREAD

**Issue by Joyguo** [s5z/zsim#49]
I use ZSim + DRAMSim2 to simulate the heterogenous memory system, so there are two memory controllers with different configurations. I check ZSim source code, the DRAMSimAccEvent is only created in the DRAMSimMemory::access() which is called according to LLC's parent id? Per my understand, the only interface of DRAMSim2 is addTransaction which is encapsulate into DRAMSimMemory::enqueue. I don't what the DRAMSimMemory::access() is used for? I want to do some   scheduling between two controllers. Could you please help to explain how to differentiate memory controllers? By DRAMSimAccEvent or parent id or address? Thank you.

**Comment by s5z** [comment]
When you create multiple memory controllers, zsim interleves memory addresses among them. See init.cpp:512 (SplitAddrMemory). By implementing something with similar functionality as SplitAddrMemoy, you can control the scheduling of memory across controllers.
