### ISSUE TITLE
Running het.cfg configuration example returns errors

### ISSUE THREAD

**Issue by imanehaf** [s5z/zsim#51]
Hello,

I am quite new to ZSim so I went through the documentation, issues and the examples. The simple ones seem to work but when I run the simulation with the het.cfg configuration, it returns some errors. I only left one process:

process0 = {
    command = "$ZSIMAPPSPATH/build/parsec/blackscholes 15 2000000";
    startFastForwarded = True;
};

and I checked beforehand that the Parsec benchmark is not the issue.
The error returned is:

[H] Creating global segment, 1024 MBs
[H] Global segment shmid = 4161551
[H] Deadlock detection ON
/build/parsec/blackscholes : No such file or directory
[H] Child 11756 done
[H] All children done, exiting

When I change the command to be run as an executable:

command = "./$ZSIMAPPSPATH/build/parsec/blackscholes 15 2000000";

I get the following:

[S 0] [0] Adjusting clocks, domain 0, de-ffwd 0
[H] Attached to global heap
[S 0] vDSO info initialized
[S 0] Started scheduler watchdog thread
[S 0] FF control Thread TID 11799
[S 0] FF thread 0 starting
[S 0] Started contention simulation thread 0
PARSEC Benchmark Suite
Usage:
	.//build/parsec/blackscholes <nthreads> <inputFile> <outputFile>
[S 0] Shadow/NOP thread 0 finished
[S 0] Finished, code 1
[S 0] Dumping termination stats
[H] Child 11794 done
[H] All children done, exiting

Any help with this would be greatly appreciated. 
Thanks.

**Comment by hlitz** [comment]
did you try absolute paths?

**Comment by imanehaf** [comment]
Hello Hiltz,

Yes, thank you, that solves the 'no such file' error but I still have the second error:

Usage:	build/parsec/blackscholes <nthreads> <inputFile> <outputFile>

Do I put the arguments in the attribute 'input'? 
I understood that 15 is the number of threads but what does '20000' represent here?

**Comment by s5z** [comment]
Maybe blackscholes has changed in later PARSEC versions. In PARSEC v1 and v2, the second parameter controls the amount of work to do, and there is no input file.
