### ISSUE TITLE
Understanding how contention simulation occurs

### ISSUE THREAD

**Issue by kartikram3** [s5z/zsim#53]
I am confused about a few things that happen during the weave phase.

1. Domain crossing events :

In the paper, it says that domain crossing events are created during the weave phase (contention simulation) when a parent finishes and its child happens to be in another domain.

However, in the code, some crossings are produced during the function CoreRecorder::recordAccess(unint64_t startCycle) . This function is called very frequently by the core recorder, which means crossings are also produced outside of contention simulation (during the bound phase). How are we able to create crossings beforehand in this manner.

2. Managing timing records :

A second question I had is how the event recorder works. In my understanding, the zinfo->eventRecorders contain one timing record for each core. Whenever a new event is to be recorded, the timing record is popped out using the popRecord() function, modified using the "addChild" function and then pushed back in using the pushRecord() function. However, this is not the case during the CoreRecorder::recordAccess(unint64_t startCycle) function. The timing record is popped out but never pushed back, which leaves the core recorder with no timing record. 

So how do we maintain the event graph (fig 4 of the paper) if it frequently gets emptied in this manner. I am not sure that the event graph is maintained in the event recorder. If not, where can I find it ?

3. Printing the event graph

I am wondering how to print the event graph at the end of contention sim. That would give me a good handle on how the weave phse works, as I could make some changes to the code and see the effect on the event graph. I'd like to print it out at the start of the ContentionSim::simulatePhaseThread function, but right now, am not sure which data structure contains the event graph or if it has already been emptied into the priority queue.

4. 0  minStartCycle events :

For now, I printed the priority queue of each domain as it dequeues in order to check what the minimum start cycle of each phase is. Surprisingly, many events had a minStartCycle of 0. What are these events ?

The code I added was : 

 info("Event has min start cycle %d\n",(int)te->getMinStartCycle()); 

after each 

TimingEvent* te = pq.dequeue(cycle); 
There were 3 dequeues at 3 separate locations.

==============================
[S 0] Event has min start cycle 664942

[S 0] Event has min start cycle 664974

[S 0] Event has min start cycle 664976

[S 0] Event has min start cycle 0

[S 0] Event has min start cycle 0

[S 0] Event has min start cycle 665065

[S 0] Event has min start cycle 665067

[S 0] Event has min start cycle 665252

[S 0] Event has min start cycle 665276

[S 0] Event has min start cycle 665310

[S 0] Event has min start cycle 0

[S 0] Event has min start cycle 665401

[S 0] Event has min start cycle 665792

[S 0] Event has min start cycle 665814

[S 0] Event has min start cycle 665848

[S 0] Event has min start cycle 0

[S 0] Event has min start cycle 665939

...
===================================

I used the default pgo.cfg while running this simulation. The test program specified was a simple for loop that increments a counter.

**Comment by s5z** [comment]
1. IIRC the paper does not say domain crossing events are created during the weave phase. They are created in the bound phase, and executed in the weave phase, as you have observed.

2. Timing records != events. Timing records are used to communicate throughout the hierarchy what events are created in response to an access. The cores connect the start and end events of each timing record to their own internal events. But timing records do not survive past an access.

3. You can walk the event graph at the beginning of each weave phase, and print it as you go.

4. Those are probably DelayEvents, which implement a fixed delay. DelayEvents are specialized, and don't go through the priority queue.

**Comment by kartikram3** [comment]
1. Thanks, that makes sense now. The domain crossing event was introduced in the weave phase description section so I assumed it was also created then.

2. Thanks for clearing that up. It makes sense that the record contains all the events corresponding to the current access.

3. I was having difficulty locating the event graph. From what I can see, the events in the timing records for each access are enqueued into the priority queue of the corresponding domain in the "recordAccess" function I mentioned in the original post. 
Is there a DAG (directed acyclic graph) of all the events for the weave phase(like fig 4 of the paper) or do we only have the set of priority queues for each domain which is then processed during weave ?

4. Yes that makes sense. Are the delay events so that two accesses to the same cache have some minimum access latency separation ?

**Comment by s5z** [comment]
3. It's not available anywhere, but you can use methods inside Event to walk the event DAG.

4. Among other things. They are used heavily, that's why they are specialized.

**Comment by kartikram3** [comment]
Thanks this has helped a lot in understanding the weave phase :) :+1:

**Comment by s5z** [comment]
You're welcome!
