### ISSUE TITLE
How to differentiate read/write latencies?

### ISSUE THREAD

**Issue by SIGARCH** [s5z/zsim#59]
Hello,

I'm trying to implement asymmetric read/write latencies in caches.
Currently, both latencies are same (accLat).
You mentioned "could split in get/put, probably not needed".

It looks that we can just replace respCycle += accLat; with respCycle += wrLat; in both Simple and Timing caches if req.type == PUTX in the access() method.
However, it's difficult to implement it for the replacement when GETS and GETX misses occur due to several events. In addition, Simple and Timing caches have different structures for handling them.
(I exclude the PUTS because it never incurs write operation.)

Is it possible that response follows the accLat and replacement does wrLat?
And, does current zsim support to prevent next access while replacing?
Please give some hints for hacking them.

Thank you.

**Comment by s5z** [comment]
Take a look at TimingCache, which has a more sophisticated timing model, includes contention for array accesses due to hits, fills, and replacements, and has limited MSHRs. You could change write accesses to be slower in this model.
