### ISSUE TITLE
Does tcc lock matter

### ISSUE THREAD

**Issue by kartikram3** [s5z/zsim#61]
TCC (top coherence controller) lock serializes up accesses (eg : from L1 to L2 to L3). However, only one thread at a time (the one joined to the core) ever competes for this lock. Invalidation accesses from other cores never acquire the tcc. 

If only one thread at a time ever competes for tcc the lock, then it seems that we do not need it. Is tcc included in case we want to include SMT(simultaneous multithreading) in zsim  in the future (more than one thread per core).?

**Comment by s5z** [comment]
Try to disable it and see what happens :)

TCC is used to block multiple access requests (GETS/X, PUTS/X) going up the same path, but TCC and BCC are locked and unlocked in a very specific order when requests traverse levels. This allows invalidation and downgrade requests going down to win over an access request going up, avoiding deadlock while maintaining a reasonably easy concurrency model (only one thread is operating on a cache bank at a given time, and there are limited races). Note that requests going down the hierarchy only grab BCC.

This means every time you have an access request go up a level and start from anything other than I (e.g., an S->M upgrade or a PUTS/PUTX), you may get an intervening downgrade or invalidate. The protocol handles those in a fairly contained way (see CheckForMESIRace). Also worth noting: these are not all the races you can have in a real protocol with completely unordered point-to-point links.

**Comment by kartikram3** [comment]
I ran astar for 100 million instructions using U Ghent's pinpoints, but
there was no difference in result when tcc locking is disabled.

I guess my question can be better framed as :

In what scenario do we have multiple concurrent 'up' accesses in a cache
hierarchy ? Only in this scenario we would require the 'tcc' lock. From
what I can see, INV and INVX ('down') accesses can race with the up
accesses, but they don't generate additional up accesses of their own.

I think CheckForMESIRace makes sense because the INV or INVX may get the
bcc first and thus change the state of the cache lines/ do writebacks,
which means we have to change our up accesses(GETX, PUTX, PUTS)
accordingly. I totally agree that we can have crazy race scenarios in a
more general protocol. In fact, that is something I am working on as I need
to change the coherence protocol a bit for my project.

[image: Inline image 1]

**Comment by s5z** [comment]
You won't see a difference on single-threaded programs. But with multi-threaded or multi-programmed workloads, disabling tcc will break the protocol.

**Comment by s5z** [comment]
You will only get concurrent bound-phase accesses when simulating multiple threads. Functional (bound-phase) simulation happens one access at a time for each core, even when those accesses are overlapped in time.

**Comment by kartikram3** [comment]
I tried with multiprogrammed astar (2 processes) on simple.cfg , which is a single core. There was not much difference in the simulation result.

s5z >> You will only get concurrent bound-phase accesses when simulating multiple threads. Functional (bound-phase) simulation happens one access at a time for each core, even when those accesses are overlapped in time.

I thought that the simulated cores are single threaded , in the current model. So multiple threads would round robin schedule on the simulated core and not run in parallel. Am I correct in thinking this ? I have a feeling this is where I am not correct :)

![image](https://cloud.githubusercontent.com/assets/4967121/8946735/8b22f628-3558-11e5-924a-d48fb8d1b75a.png)

**Comment by s5z** [comment]
You're right. In a single-core system, the scheduler will serialize your threads. But multi-programming experiments on systems with multiple cores will have concurrent accesses.

**Comment by kartikram3** [comment]
OK thanks.

Which function schedules the host threads within a phase ?  
I found that the TakeBarrier fn synchronizes threads at the end of the phase.
However, I am not sure how the pin threads are scheduled inside of a phase.

This would help me understand how the concurrent 'up' accesses happen.

**Comment by kartikram3** [comment]
I ran het.cfg (which has many cores) using two astar processes. Even here there was not significant difference with and without the tcc lock.

![image](https://cloud.githubusercontent.com/assets/4967121/8949708/63e2a6c0-357c-11e5-90fd-cac0126e0586.png)

**Comment by kartikram3** [comment]
I double checked with the paper which says that only one host thread is mapped to each simulated core (at any point of time)

This seems to imply that we do not have concurrent "up" accesses. (i.e. concurrent GETX, GETS, PUTS, PUTX ) corresponding to a particular core in which case we don't need tcc locking.

**Comment by s5z** [comment]
Check the program you're using causes frequent PUTs and INVs between the LLC and L2s, otherwise you won't hit the race. This may also need a hierarchy in which your shared level is not unlocked by the parent (caches unlock the child to prevent races, but main memories happen to not do this).

**Comment by kartikram3** [comment]
Got it. The shared part of the hierarchy would definitely have concurrent accesses "up" for which we need 'tcc' for serialization. I totally forgot abt these hierarchiies.

For the race to be activated, we would need more than one shared "cache 'level,, eg: shared L3, then L4  and then memory. Then tcc would prevent the "up" accesses from deadlocking. Eg : If some access (A1) reached L4 and another access from a different core(A2) reached L3, then they would deadlock without tcc, because A1 would ask for the L3 lock and A2 would ask for the L4 lock and they won't give each other the locks.  until they get each other's locks. So deadlock. With "tcc" lock, A2 access would wait at L3 until A1 finished L4 access, comes back down to L3, finishes there and goes back to L2.  So deadlock averted due to serialization.

In the case of the L1->L2->L3 (shared LLC), it does not need tcc because there is only 1 shared level. 
s5z >> This may also need a hierarchy in which your shared level is not unlocked by the parent (caches unlock the child to prevent races, but main memories happen to not do this).
So I think you are hinting towards that in this comment.

I think I understand the use case of tcc finally ! :o
