### ISSUE TITLE
Read vs. write access in cache

### ISSUE THREAD

**Issue by lordmeph** [s5z/zsim#63]
Hi,

I am new to zsim and have a small question. Is there a possibility to distinguish between a read and a write access to a particular cache, e.g. L1-D? Thank you!

Kind Regards!

**Comment by s5z** [comment]
Yes, see the load() vs store() methods of FilterCache. For every other cache, other events are profiled, e.g., GET requests read data with different levels of permission, PUTS is a clean writeback, and PUTX is a dirty writeback. However, these do not correspond directly with load or store accesses in the program.
