### ISSUE TITLE
Assertion failed in contention sim using non inclusive hack with ddr memory

### ISSUE THREAD

**Issue by kartikram3** [s5z/zsim#64]
Consider the L1,L2 private and L3 shared cache hierarchy.
I use simple cache for all levels. The 2 cores are ooo core, not timing core.
The 2 processes are both astar from the SPEC 2006 suite.

If I add non inclusive hack to the L3 shared cache, then during contention sim,
the assertion for ddr memory access occasionally fails. The assertion is that 
the startCycle  > minStartCycle for the timing event.

Is this caused by bypass writebacks that occur due to the noninclusive hack ?
I'm wondering how to fix this. The error does not occur for simple memory or single
core simulations.

EDIT :
I confirmed that it is caused by the bypass writebacks. If I comment that out and just invalidate the line where the eviction occurs, then the error does not occur. Now the question is why the bypass writebacks mess up the contention simulation.

UPDATE : 
It seems that the problem lay in the section of code in cache.cpp, where the timing records are
stitched together because sometimes there are multiple timing records created due to writebacks. 
This code needs to be updated for the use case of this post.

**Comment by s5z** [comment]
nonInclusiveHack is called nonInclusiveHack for a reason ;). See issue #62. You'd be better off coding a simple non-inclusive cache with a separate directory.
