### ISSUE TITLE
L1 access latencies

### ISSUE THREAD

**Issue by loiron** [s5z/zsim#66]
Hello,

In the init.cpp is stated that terminal caches has no access latency b/c it is assumed accLat is hidden by the pipeline:  "uint32_t accLat = (isTerminal)? 0 : latency;".

However, in the L1D case, the constant "L1D_LAT"  is added to the latency calculated in "l1d->load(...)" for calculating the total latency. Why is this constant used instead of the one in the configuration file?

Furthermore, in the L1I accesses, there is not  such a constant. We asumme that is here when the access latency is hidden by the pipeline. But, for example, if you want to simulate a big instruction cache with high latency (lets say, 8 cycles), How this affects to the correctness of this model? 

Thank you very much

**Comment by s5z** [comment]
The assumption is that *both* L1s are integrated in the pipeline. In OOO cores, L1I latency is implicitly determined by the difference between FETCH and DECODE stages. If you want to simulate longer pipelines, change FETCH/DECODE/ISSUE/DISPATCH_STAGE to simulate a longer pipe. The configurable l1i/l1d.latency is only used for the invalidation latency.

In theory, you could change some of these into variables, but it'd be less efficient (gcc does a lot of constant folding).
