### ISSUE TITLE
How to model a certain topology?

### ISSUE THREAD

**Issue by yueyueniao187** [s5z/zsim#69]
If zsim does not  assume a topology, we only use latency to model a mesh topology, right?
I'm not quite sure.

**Comment by DaFun** [comment]
You set fixed net delay in network file. But I don't know why zsim doesn't have a contention delay model. Without contention delay model, your mesh network must be not complete.

**Comment by s5z** [comment]
We have a network model with contention internally. Should be coming soon, stay tuned!

**Comment by jgonzalezr** [comment]
Any news about the network model? Will it be available soon?

**Comment by manwu1994** [comment]
Any news about the network model?
