### ISSUE TITLE
Register Values

### ISSUE THREAD

**Issue by loiron** [s5z/zsim#70]
Hello,

I need to know the register's content of each uop, the value of the input registers and the output registers (rs and rd).

For doing that, I guess that I need  to use IARG_REG_VALUE in the PIN instrumentation calls, and read the memory values in the load operations. I'm missing something?

I wonder if doing this in zsim is a good idea, or if it is not the best simulator for doing that.

Thank you very much

**Comment by s5z** [comment]
Sounds like this would be straightforward to do. The one thing you need to keep in mind though is that zsim does not execute wrong-patch instructions.
