### ISSUE TITLE
Problems compiling ZSIM with HDF5

### ISSUE THREAD

**Issue by Dragonslair5** [s5z/zsim#73]
I am trying to compile ZSIM using the command **scons -j16** like instructed on **README.md**, but i am facing problems with **HDF5**.

First, the directive **#include \<hdf5.h\>**  was not working due to the path from the actual **hdf5.h** file. It was not directly in **/usr/include**, but in a subfolder **/usr/include/hdf5/serial**. After including the subfolder in every **.cpp** that makes reference to **hdf5.h**, the result from **scons -j16** is the following:

-------------------------------------------
scons: Reading SConscript files ...
Building opt zsim at build/opt
scons: done reading SConscript files.
scons: Building targets ...
g++ -o build/opt/dumptrace build/opt/dumptrace.ot build/opt/access_tracing.ot build/opt/memory_hierarchy.ot build/opt/config.ot build/opt/galloc.ot build/opt/log.ot build/opt/pin_cmd.ot -lconfig++ -lhdf5 -lhdf5_hl
**/usr/bin/ld: cannot find -lhdf5**
**/usr/bin/ld: cannot find -lhdf5_hl**
collect2: error: ld returned 1 exit status
g++ -o build/opt/libzsim.so -Wl,--hash-style=sysv -Wl,-Bsymbolic -Wl,--version-script=/home/mau/Dragons_Lair5/PIN/pin-2.14-71313-gcc.4.4.7-linux/source/include/pin/pintool.ver -shared build/opt/ooo_core.os build/opt/prefetcher.os build/opt/tracing_cache.os build/opt/virt/virt.os build/opt/text_stats.os build/opt/proc_stats.os build/opt/init.os build/opt/contention_sim.os build/opt/ddr_mem.os build/opt/detailed_mem.os build/opt/stats_filter.os build/opt/ooo_core_recorder.os build/opt/partition_mapper.os build/opt/utility_monitor.os build/opt/scheduler.os build/opt/timing_event.os build/opt/galloc.os build/opt/decoder.os build/opt/timing_core.os build/opt/virt/timeout.os build/opt/hdf5_stats.os build/opt/timing_cache.os build/opt/process_tree.os build/opt/monitor.os build/opt/access_tracing.os build/opt/coherence_ctrls.os build/opt/virt/time.os build/opt/dramsim_mem_ctrl.os build/opt/log.os build/opt/virt/fs.os build/opt/mem_ctrls.os build/opt/virt/syscall_name.os build/opt/network.os build/opt/debug_zsim.os build/opt/hash.os build/opt/cache_arrays.os build/opt/null_core.os build/opt/zsim.os build/opt/virt/ports.os build/opt/detailed_mem_params.os build/opt/core_recorder.os build/opt/lookahead.os build/opt/simple_core.os build/opt/trace_driver.os build/opt/cache.os build/opt/config.os build/opt/pin_cmd.os build/opt/virt/cpu.os build/opt/process_stats.os build/opt/memory_hierarchy.os -L/usr/lib -L/usr/lib/x86_64-linux-gnu -L/home/mau/Dragons_Lair5/PIN/pin-2.14-71313-gcc.4.4.7-linux/extras/xed-intel64/lib -L/home/mau/Dragons_Lair5/PIN/pin-2.14-71313-gcc.4.4.7-linux/intel64/lib -L/home/mau/Dragons_Lair5/PIN/pin-2.14-71313-gcc.4.4.7-linux/intel64/lib-ext -lconfig++ -lpin -lxed -lpindwarf -lelf -ldl -lrt -lhdf5 -lhdf5_hl
g++ -o build/opt/sorttrace build/opt/sorttrace.ot build/opt/access_tracing.ot build/opt/config.ot build/opt/galloc.ot build/opt/log.ot build/opt/pin_cmd.ot -lconfig++ -lhdf5 -lhdf5_hl
printf "#define ZSIM_BUILDDATE \"`date`\"\n#define ZSIM_BUILDVERSION \"`python misc/gitver.py`\"" >>build/opt/version.h
/usr/bin/ld: cannot find -lhdf5
/usr/bin/ld: cannot find -lhdf5_hl
collect2: error: ld returned 1 exit status
scons: *** [build/opt/dumptrace] Error 1
scons: *** [build/opt/sorttrace] Error 1
/usr/bin/ld: cannot find -lhdf5
/usr/bin/ld: cannot find -lhdf5_hl
collect2: error: ld returned 1 exit status
scons: *** [build/opt/libzsim.so] Error 1
scons: building terminated because of errors.

----------------------------------------

So the linker might not been able to find the file **hdf5.a**. I checked the other libraries that seems not to be having linker problems, like **libelf.a**, and it is located on **/usr/lib/x86_64-linux-gnu** folder. **libhdf5.a** is located in a subfolder (just like **hdf5.h** is).

**Any idea how to solve this?**

im trying to install ZSIM on **Ubuntu 15.04 64b** using **libhdf5 version 1.8.13**

**Comment by hlitz** [comment]
Why didn't you add include dir and library dir in the SConscript file 
instead of modifying the source files?

also check that you have the hdf5 dev package.

**Comment by Dragonslair5** [comment]
I checked if hdf5 is installed in the following way: **dkpg -s libhdf5-dev**
it says it is installed.

I included the path to the hdf5 libs on /ust/libs/ folder in the PINLIBPATH (line 92 of **SConstruct**) variable in the following way:
____
env["PINLIBPATH"] = ["/usr/lib", "/usr/lib/x86_64-linux-gnu", **"/usr/lib/x86_64-linux-gnu/hdf5/serial"**, joinpath(PINPATH, "extras/" + xedName + "-intel64/lib"), joinpath(PINPATH, "intel64/lib"), joinpath(PINPATH, "intel64/lib-ext")]
_____

And here is the result:

_____
scons: Reading SConscript files ...
Building opt zsim at build/opt
scons: done reading SConscript files.
scons: Building targets ...
g++ -o build/opt/dumptrace build/opt/dumptrace.ot build/opt/access_tracing.ot build/opt/memory_hierarchy.ot build/opt/config.ot build/opt/galloc.ot build/opt/log.ot build/opt/pin_cmd.ot -lconfig++ -lhdf5 -lhdf5_hl
**/usr/bin/ld: cannot find -lhdf5**
**/usr/bin/ld: cannot find -lhdf5_hl**
collect2: error: ld returned 1 exit status
scons: *** [build/opt/libzsim.so] Implicit dependency `**/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so**' not found, needed by target `build/opt/libzsim.so'.
scons: *** [build/opt/dumptrace] Error 1
scons: building terminated because of errors.
___

libhdf5 is still not being found in one case.

The file **/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so**  seems indeed not to exist. There is a **libhdf5.so** being listed by **ls** in that folder, but its listed in red color with a darker background, indicating it might be a broken symlink and not a actual file. I shall take a deeper look on this.

_____

About **SConscript**, i didnt look through this file yet. There seems to be two of them, one in **zsim/src** and another one in **zsim/build/opt**, which one do I modify?

**Comment by Dragonslair5** [comment]
I got it working. Did the inclusion of different ".h" and ".a" in the SConstruct and installed libconfig-dev and libhdf5-dev not using the package manager (libhdf5.so was indeed inexistent). But now I am having the problem described in issue #72.
