### ISSUE TITLE
Simulating exclusive caches

### ISSUE THREAD

**Issue by moncefmechri** [s5z/zsim#75]
Hello,

I am interested in simulating hierarchies of exclusive caches. Just something simple to start with, a single-core with 2 levels of cache that are mutually exclusive.

Is it something supported by Zsim? The only thing I could find related to this was this post: https://github.com/s5z/zsim/issues/62

It does mention exclusive caches, and among other things, "Internally, we've moved away from nonInclusiveHack, and have simple non-inclusive and exclusive cache models". But I couldn't really find how to use this.

Any help would be very appreciated.
Regards,
Moncef.

**Comment by s5z** [comment]
#62 is a good starting point. If you do not need coherence, exclusive caches are quite simple to implement. But there are no publicly available implementations yet (we have not gotten around to releasing ours yet).
