### ISSUE TITLE
assert in phase_slab_alloc.h

### ISSUE THREAD

**Issue by loiron** [s5z/zsim#79]
Hello,

I am creating a modification of the OOO core, creating a new file, and adding the corresponding code in the contention_sim.cpp and init.cpp.

I have several of this modifications (several OOO core implementations), but with some of them, this error occurs at execution time:

[S 0] Thread 0 starting
[S 0] Failed assertion on build/opt/phase_slab_alloc.h:153 'sz < slabSize' (with '104 < 0')

Only happens when operates with weave models (timing cache or ddr).

And, for example, it works correctly for OOOCore1, but incorrectly with OOOCore2 when both cores are exactly the same...

What could be causing this? Any clue or suggestion will help

Thank you very much

**Comment by s5z** [comment]
You seem to be using an old version of the code... phase_slab_alloc does not exist anymore. We switched to a more robust slab allocator for events (the old one used some conservative thresholds to recycle slabs with very old events, which sometimes caused memory corruption with extreme amounts of contention; the new one uses reference counting and does not have this problem). Can you pull and check?
