### ISSUE TITLE
Pin a process to a core

### ISSUE THREAD

**Issue by nmittal18** [s5z/zsim#81]
Hi.. I have just started using ZSIM. I am trying to figure out if there is a way to pin a process to core. Is there a direct way to do this ? Thanks..

**Comment by benpatsai** [comment]
Yes, you can pin a process to cores by using the "mask" parameter in the config file. For example:

    process0 = {
        ...
        mask = "0"
        ...
    };

pins process 0 to core 0.

You can also pin a multi-threaded process to a set of cores. For example

    process0 = {
        ...
        mask = "0 1 2 3"
        ...
    };

pins process 0 to core 0~3.

**Comment by vijay4454** [comment]
Hello benpatsi. A quick follow up question on that: Is it possible to pin specific threads of a single multi-threaded process to specific cores (let the user configure a thread<->core mapping)?

**Comment by benpatsai** [comment]
Well, unfortunately, there is no such thing at this point. :(

You will have to implement a magic operation that registers your special thread in the simulator, modify the application to use it when that thread is created in the application, and then modify the scheduler.h/cpp to pin that special thread to particular core.

If you don't have the source code, then maybe you can hardcode some scheduling policy within scheduler.h/cpp to achieve something like that, but this might require the application to have static thread creating order.

**Comment by s5z** [comment]
You could implement the sched_setaffinity syscall instead of ignoring it as zsim currently does. In fact, I think @gaomy3832 has something similar. Mingyu, if you can, please submit a pull request.

**Comment by gaomy3832** [comment]
Hi Daniel, I have worked on this for a bit but there are several questions I would like to discuss with you before commit. I have sent you an email directly in last December. Please let me know your opinions so I can continue to finish it.
