### ISSUE TITLE
Problem with finding correct version of libstdc++.so.6

### ISSUE THREAD

**Issue by vijay4454** [s5z/zsim#86]
I compiled zsim using gcc 4.6.4 on a red hat machine with Linux 2.6.32. I am using pin-2.14-67254-gcc.4.4.7-linux. 

When running the simple test, I get the following error:

[thiruven@altair] (52)$ ./build/opt/zsim tests/simple.cfg 
[H] Starting zsim, built Thu Jan  7 12:41:03 CST 2016 (rev master:83:21a03d4:1fc 3+ 9fda6b3c)
[H] Creating global segment, 1024 MBs
[H] Global segment shmid = 124190734
[H] Deadlock detection ON
E:E:Unable to load /scratch.1/thiruven/mpu_project/zsim/build/opt/libzsim.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /scratch.1/thiruven/mpu_project/zsim/build/opt/libzsim.so)
Unable to load /scratch.1/thiruven/mpu_project/zsim/build/opt/libzsim.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /scratch.1/thiruven/mpu_project/zsim/build/opt/libzsim.so)
[H] Child 21721 done
[H] Child 21722 done
[H] All children done, exiting

The libstdc++ in the /usr/lib64 has been compiled with a different version of GCC. So I added the path to gcc-4.6.4's libstdc++ in the LD_LIBRARY_PATH. That is being reflected correctly when I do 'ldd libzsim.so'. 

[thiruven@altair] (26)$ ldd build/opt/libzsim.so 
	linux-vdso.so.1 =>  (0x00007fff21e5e000)
	libconfig++.so.9 => /u/t/h/thiruven/local/lib/libconfig/lib/libconfig++.so.9 (0x00007f7a4faab000)
	libelf.so.0 => /u/t/h/thiruven/local/lib/libelf/lib/libelf.so.0 (0x00007f7a4f893000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f7a4f667000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f7a4f45f000)
	libhdf5.so.6 => /usr/lib64/libhdf5.so.6 (0x00007f7a4ee76000)
	libhdf5_hl.so.6 => /usr/lib64/libhdf5_hl.so.6 (0x00007f7a4ec44000)
	libstdc++.so.6 => /s/gcc-4.6.4/amd64_rhel6/lib64/libstdc++.so.6 (0x00007f7a4e940000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f7a4e6bb000)
	libgcc_s.so.1 => /s/gcc-4.6.4/amd64_rhel6/lib64/libgcc_s.so.1 (0x00007f7a4e4a6000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f7a4e112000)
	/lib64/ld-linux-x86-64.so.2 (0x0000003296c00000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f7a4def4000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f7a4dcde000)

Now, I don't understand why the 'zsim' binary is looking for libstdc++ in the /usr/lib64, not at /s/gcc-4.6.4/amd64_rhel6/lib64/. Can someone hint at what I should do to fix this?

**Comment by s5z** [comment]
Pin does not use LD_LIBRARY_PATH for the pintool (it does only for the application). You can (a) use Pin's env vars to set the Pintool's LD_LIBRARY_PATH (see the manual), or (b) add the path to the pintool's runpath or rpath (use the right linker options or edit the binary with patchelf).
