### ISSUE TITLE
Is it OK to use timing cache with OOO Core

### ISSUE THREAD

**Issue by kartikram3** [s5z/zsim#87]
There is a comment in one of the source files that says you must use timing cache with timing core.
However, I could use timing cache with OOO core too, with no errors. Is it OK to do this, or does OOO core require a different timing cache model ?

**Comment by benpatsai** [comment]
You can think of OOO core as a timing core with OOO execution. So it is perfectly fine to use OOO core with timing cache.

**Comment by kartikram3** [comment]
Thats great ! Thanks !
