### ISSUE TITLE
Accessing periodic dumped stats

### ISSUE THREAD

**Issue by kartikram3** [s5z/zsim#89]
I want to access cache stats such as INV, GETS, GETX etc. every 100 phases. So I set the stat phase interval to 100. However, I don't know where the results are dumped. 

There are 3 h5 files generated by the simulation -- zsim.h5, zsim-ev.h5 and zsim-cmp.h5
Using hdfview, I could see some of the dumped stats in zsim.h5, such as  root->time, root->trigger, root->procCycles and others, at different phases of the simulation. However, I could not find the cache stats.

I am able to access cache stats at the end of the simulation using README.stats to parse zsim-ev.h5, so I know the stats are definitely updated during the simulation.

**Comment by gaomy3832** [comment]
Normally all stats are periodically dumped. However there is a config option "procStatsFilter" under "sim" in the cfg file allowing to filter out some stats to save .h5 file size. Make sure you didn't filter out the cache stats there (which is the case in tests/simple.cfg.

Also I suggest you read README.stats. It tells you how to access the stats (using python) and their format.

**Comment by kartikram3** [comment]
Thanks !
I can access the periodic stats using the python script. Surprisingly, the hdfview program does not display the cache and core stats although they can be read by the python script.

I wonder why hdfview only displays partial statistics !

![image](https://cloud.githubusercontent.com/assets/4967121/12375800/3f1c4f7c-bc99-11e5-9f7d-e8a9a3689269.png)
