### ISSUE TITLE
simulate failed when running multi-processes after adding TLB simulation in zsim

### ISSUE THREAD

**Issue by cyjseagull** [s5z/zsim#90]
hello,
       I have added TLB simulation in zsim, which is comprised of TLB, page table walker and page table, number of TLBs and page table walkers is equal to 2*cpu_num and cpu_num; page table number is equal to number of processes. However, after adding these simulations, multi-processes can't work normally, while multi-threading single process simulation can work normally. Is there any  specials about multi-process simulation I haven't notices ? Looking forward to and appreciate for  your response !

**Comment by benpatsai** [comment]
Hi, 

Can you briefly describe how you implement TLB simulations? I did the same thing for TLB structures only before, but did not encounter any problem. 

Also, you might want to know that in Zsim, the address space are partitioned using process ids, so in your page table, you need to read the address mapping in /proc/maps/ to detect the real sharing pattern between processes.

Po-An

**Comment by s5z** [comment]
My guess is you're probably using non-globally-allocated memory. See galloc.h. We can't help you debug private code with so little info.

**Comment by cyjseagull** [comment]
Hi,
   Thanks for your response! When implementing TLB, I add a tlb translation function in files ooo_core.* and timing_core.*, before load/store/branch/bbl operation, call this function firstly to translate virtual address into physical address.
   Besides, I have implemented a simple buddy allocator in zsim which is used to allocate physical pages for virtual pages, when page fault, it will use buddy allocator to allocate a free page firstly, then a mapping from virtual page to physical page will be added in page table.
  In my implementation, every process owns a page table; every core owns a instruction TLB, a data TLB and a  page table walker. And I have ignored sharing pattern between processes.
  Maybe s5z is right, when I using "gm_memalign" and new to create object, some problem has disappeared. Can you tell me in which case to use "gm_mamalign and placement new" to create object instead of new? Looking forward to your response!
