### ISSUE TITLE
in which case using gm_memalign to allocate object in zsim

### ISSUE THREAD

**Issue by cyjseagull** [s5z/zsim#93]
hi,

  I am using zsim to do some simulation of TLB, however, I cann't figure out the differences between gm_memalign and new, in file "src/init.cpp", some objects created with "new", others created with "gm_memalign", then initialized with placement new. I will appreciate for your  response.

**Comment by s5z** [comment]
gm_malloc/gm_calloc/gm_memalign, etc, allocate from the global heap. If an object inherits from GlobAlloc (see galloc.h), new and delete also use the global heap. If you are adding new simulator objects, e.g., a TLB, you can use new as long as you inherit from GlobAlloc.

**Comment by cyjseagull** [comment]
Thanks to your elaborate response, I have solved the problem encountered when simulating TLB. Thank you very much!
