### ISSUE TITLE
Different frequencies for different cores

### ISSUE THREAD

**Issue by vijay4454** [s5z/zsim#98]
I am wondering how to set different frequencies for different cores in a heterogeneous core configuration. Right now, it looks like the core frequency of all cores is set to whatever 'frequency' parameter is set in the configuration file. The access latency of all configured caches must also be computed by the user based on the above frequency and placed in the configuration file.

Is it an easy source code change to add the functionality of different frequencies for different cores? I am guessing that the only change that is required is to the cache access latency handling. It looks like I need to somehow change the source code to allow the configuration of cache access latency in nanoseconds instead of cycles, allow a new 'core frequency' configuration for each configured core and retain the 'global' frequency parameter as the system frequency at which memory controller communicates with the memory.

Am I right? Are there any other changes required?

**Comment by s5z** [comment]
Yes, this is quite doable. You can check the code that does the frequency conversion in DDRMem to see how to have different components clocked at different frequencies. Basically, you need a high enough "system frequency" and a translation function between core and system cycles. Every time you do a cache access, you compute the cycles in system frequency, then translate back when you get the response.

**Comment by ranganathamk** [comment]
Hi vijay4454,

I am relatively new to zsim.

Were you able to configure zsim with different core frequencies?

I am trying to do the exactly same. I am planning to have a core group of 4 to work at one frequency (f1) and another core group of 4 to work at another frequency (f2). In this case, should I have the higher frequency among f1 and f2 as the system frequency?

Also, I didn't understand why we need to only worry about the cache access latency. I was thinking we need to also take care of the internal working of the cores. 

Thanks!

**Comment by vijay4454** [comment]
Yes, I was able to do it (did what was suggested by @s5z above). You need to set system frequency as the higher of the two frequencies and set all cache latencies in terms of the system frequency. 

You are right, this frequency issue also affects the cycle counts of operations inside the core that take more than 1 cycle. However, I was using the SimpleCore type for the other type of core I configured (with a different frequency) and this type of core is set up to execute all instructions in a single cycle except of course the memory instructions. So I didn't have to adjust any internal operation cycle counts, just had to adjust the cycle count of memory accesses using the ratio of system frequency and core frequency.

**Comment by ranganathamk** [comment]
Thank you for the quick response.
