### ISSUE TITLE
how to run TPC-C and big data benchmark in zsim

### ISSUE THREAD

**Issue by cyjseagull** [s5z/zsim#99]
Hello,

       I am doing some experiments using zsim, and I need to know the memory access pattern of some transaction type benchmarks such as TPC-C, however, when I ran them with zsim, it generated a lot of errors, can zsim run TPC-C？ And how can I run it with CPU ? Looking forward to your response ^_^

**Comment by s5z** [comment]
You don't provide enough information for us to help...
